using System;

namespace System.Net
{
	internal enum CertificateProblem
	{
		OK,
		TrustNOSIGNATURE = -2146762496,
		CertEXPIRED,
		CertVALIDITYPERIODNESTING,
		CertROLE,
		CertPATHLENCONST,
		CertCRITICAL,
		CertPURPOSE,
		CertISSUERCHAINING,
		CertMALFORMED,
		CertUNTRUSTEDROOT,
		CertCHAINING,
		CertREVOKED = -2146762484,
		CertUNTRUSTEDTESTROOT,
		CertREVOCATION_FAILURE,
		CertCN_NO_MATCH,
		CertWRONG_USAGE,
		TrustEXPLICITDISTRUST,
		CertUNTRUSTEDCA,
		CertINVALIDPOLICY,
		CertINVALIDNAME,
		CryptNOREVOCATIONCHECK = -2146885614,
		CryptREVOCATIONOFFLINE,
		TrustSYSTEMERROR = -2146869247,
		TrustNOSIGNERCERT,
		TrustCOUNTERSIGNER,
		TrustCERTSIGNATURE,
		TrustTIMESTAMP,
		TrustBADDIGEST = -2146869232,
		TrustBASICCONSTRAINTS = -2146869223,
		TrustFINANCIALCRITERIA = -2146869218
	}
}
