using System;

namespace System.Net
{
	public enum HttpStatusCode
	{
		Continue = 100,
		SwitchingProtocols,
		Processing,
		EarlyHints,
		OK = 200,
		Created,
		Accepted,
		NonAuthoritativeInformation,
		NoContent,
		ResetContent,
		PartialContent,
		MultiStatus,
		AlreadyReported,
		IMUsed = 226,
		MultipleChoices = 300,
		Ambiguous = 300,
		MovedPermanently,
		Moved = 301,
		Found,
		Redirect = 302,
		SeeOther,
		RedirectMethod = 303,
		NotModified,
		UseProxy,
		Unused,
		TemporaryRedirect,
		RedirectKeepVerb = 307,
		PermanentRedirect,
		BadRequest = 400,
		Unauthorized,
		PaymentRequired,
		Forbidden,
		NotFound,
		MethodNotAllowed,
		NotAcceptable,
		ProxyAuthenticationRequired,
		RequestTimeout,
		Conflict,
		Gone,
		LengthRequired,
		PreconditionFailed,
		RequestEntityTooLarge,
		RequestUriTooLong,
		UnsupportedMediaType,
		RequestedRangeNotSatisfiable,
		ExpectationFailed,
		MisdirectedRequest = 421,
		UnprocessableEntity,
		Locked,
		FailedDependency,
		UpgradeRequired = 426,
		PreconditionRequired = 428,
		TooManyRequests,
		RequestHeaderFieldsTooLarge = 431,
		UnavailableForLegalReasons = 451,
		InternalServerError = 500,
		NotImplemented,
		BadGateway,
		ServiceUnavailable,
		GatewayTimeout,
		HttpVersionNotSupported,
		VariantAlsoNegotiates,
		InsufficientStorage,
		LoopDetected,
		NotExtended = 510,
		NetworkAuthenticationRequired
	}
}
