using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Collections;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Text;

namespace Microsoft.VisualBasic
{
	internal class VBCodeGenerator : global::System.CodeDom.Compiler.CodeGenerator
	{
		protected override string NullToken
		{
			get
			{
				return "Nothing";
			}
		}

		protected override void ContinueOnNewLine(string st)
		{
			base.Output.Write(st);
			base.Output.WriteLine(" _");
		}

		protected override void GenerateBinaryOperatorExpression(global::System.CodeDom.CodeBinaryOperatorExpression e)
		{
			bool flag = false;
			bool flag2 = false;
			if (e.Operator == global::System.CodeDom.CodeBinaryOperatorType.IdentityInequality)
			{
				global::System.CodeDom.CodePrimitiveExpression codePrimitiveExpression = e.Left as global::System.CodeDom.CodePrimitiveExpression;
				if (codePrimitiveExpression == null)
				{
					codePrimitiveExpression = e.Right as global::System.CodeDom.CodePrimitiveExpression;
				}
				else
				{
					flag2 = true;
				}
				flag = codePrimitiveExpression != null && codePrimitiveExpression.Value == null;
			}
			if (flag)
			{
				TextWriter output = base.Output;
				output.Write("(Not (");
				base.GenerateExpression((!flag2) ? e.Left : e.Right);
				output.Write(") Is ");
				base.GenerateExpression((!flag2) ? e.Right : e.Left);
				output.Write(')');
			}
			else
			{
				base.GenerateBinaryOperatorExpression(e);
			}
		}

		protected override void GenerateArrayCreateExpression(global::System.CodeDom.CodeArrayCreateExpression expression)
		{
			TextWriter output = base.Output;
			output.Write("New ");
			global::System.CodeDom.CodeExpressionCollection initializers = expression.Initializers;
			global::System.CodeDom.CodeTypeReference codeTypeReference = expression.CreateType;
			if (initializers.Count > 0)
			{
				this.OutputType(codeTypeReference);
				output.Write("() {");
				base.Indent++;
				this.OutputExpressionList(initializers);
				base.Indent--;
				output.Write("}");
			}
			else
			{
				for (global::System.CodeDom.CodeTypeReference codeTypeReference2 = codeTypeReference.ArrayElementType; codeTypeReference2 != null; codeTypeReference2 = codeTypeReference2.ArrayElementType)
				{
					codeTypeReference = codeTypeReference2;
				}
				this.OutputType(codeTypeReference);
				output.Write("((");
				global::System.CodeDom.CodeExpression sizeExpression = expression.SizeExpression;
				if (sizeExpression != null)
				{
					base.GenerateExpression(sizeExpression);
				}
				else
				{
					output.Write(expression.Size);
				}
				output.Write(") - 1) {}");
			}
		}

		protected override void GenerateBaseReferenceExpression(global::System.CodeDom.CodeBaseReferenceExpression expression)
		{
			base.Output.Write("MyBase");
		}

		protected override void GenerateCastExpression(global::System.CodeDom.CodeCastExpression expression)
		{
			TextWriter output = base.Output;
			output.Write("CType(");
			base.GenerateExpression(expression.Expression);
			output.Write(", ");
			this.OutputType(expression.TargetType);
			output.Write(")");
		}

		private bool AsBool(object datavalue)
		{
			return datavalue != null && datavalue is bool && (bool)datavalue;
		}

		private string OnOff(bool datavalue)
		{
			return (!datavalue) ? "Off" : "On";
		}

		protected override void GenerateCompileUnitStart(global::System.CodeDom.CodeCompileUnit compileUnit)
		{
			this.GenerateComment(new global::System.CodeDom.CodeComment("------------------------------------------------------------------------------"));
			this.GenerateComment(new global::System.CodeDom.CodeComment(" <autogenerated>"));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     This code was generated by a tool."));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     Mono Runtime Version: " + Environment.Version));
			this.GenerateComment(new global::System.CodeDom.CodeComment(string.Empty));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     Changes to this file may cause incorrect behavior and will be lost if "));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     the code is regenerated."));
			this.GenerateComment(new global::System.CodeDom.CodeComment(" </autogenerated>"));
			this.GenerateComment(new global::System.CodeDom.CodeComment("------------------------------------------------------------------------------"));
			base.Output.WriteLine();
			if (this.AsBool(compileUnit.UserData["AllowLateBound"]))
			{
				base.Output.WriteLine("Option Explicit {0}", this.OnOff(this.AsBool(compileUnit.UserData["RequireVariableDeclaration"])));
				base.Output.WriteLine("Option Strict Off");
			}
			else
			{
				base.Output.WriteLine("Option Explicit On");
				base.Output.WriteLine("Option Strict On");
			}
			base.Output.WriteLine();
		}

		protected override void GenerateCompileUnit(global::System.CodeDom.CodeCompileUnit compileUnit)
		{
			this.GenerateCompileUnitStart(compileUnit);
			this.OutputAttributes(compileUnit.AssemblyCustomAttributes, "Assembly: ", VBCodeGenerator.LineHandling.NewLine);
			base.GenerateNamespaces(compileUnit);
			this.GenerateCompileUnitEnd(compileUnit);
		}

		protected override void GenerateDelegateCreateExpression(global::System.CodeDom.CodeDelegateCreateExpression expression)
		{
			TextWriter output = base.Output;
			output.Write("AddressOf ");
			global::System.CodeDom.CodeExpression targetObject = expression.TargetObject;
			if (targetObject != null)
			{
				base.GenerateExpression(targetObject);
				base.Output.Write('.');
			}
			output.Write(expression.MethodName);
		}

		protected override void GenerateFieldReferenceExpression(global::System.CodeDom.CodeFieldReferenceExpression expression)
		{
			global::System.CodeDom.CodeExpression targetObject = expression.TargetObject;
			if (targetObject != null)
			{
				base.GenerateExpression(targetObject);
				base.Output.Write('.');
			}
			base.Output.Write(this.CreateEscapedIdentifier(expression.FieldName));
		}

		protected override void GenerateArgumentReferenceExpression(global::System.CodeDom.CodeArgumentReferenceExpression expression)
		{
			base.Output.Write(this.CreateEscapedIdentifier(expression.ParameterName));
		}

		protected override void GenerateVariableReferenceExpression(global::System.CodeDom.CodeVariableReferenceExpression expression)
		{
			base.Output.Write(this.CreateEscapedIdentifier(expression.VariableName));
		}

		protected override void GenerateIndexerExpression(global::System.CodeDom.CodeIndexerExpression expression)
		{
			TextWriter output = base.Output;
			base.GenerateExpression(expression.TargetObject);
			output.Write('(');
			this.OutputExpressionList(expression.Indices);
			output.Write(')');
		}

		protected override void GenerateArrayIndexerExpression(global::System.CodeDom.CodeArrayIndexerExpression expression)
		{
			TextWriter output = base.Output;
			base.GenerateExpression(expression.TargetObject);
			output.Write("(");
			this.OutputExpressionList(expression.Indices);
			output.Write(')');
		}

		protected override void GenerateSnippetExpression(global::System.CodeDom.CodeSnippetExpression expression)
		{
			base.Output.Write(expression.Value);
		}

		protected override void GenerateMethodInvokeExpression(global::System.CodeDom.CodeMethodInvokeExpression expression)
		{
			TextWriter output = base.Output;
			this.GenerateMethodReferenceExpression(expression.Method);
			output.Write('(');
			this.OutputExpressionList(expression.Parameters);
			output.Write(')');
		}

		protected override void GenerateMethodReferenceExpression(global::System.CodeDom.CodeMethodReferenceExpression expression)
		{
			if (expression.TargetObject != null)
			{
				base.GenerateExpression(expression.TargetObject);
				base.Output.Write('.');
			}
			base.Output.Write(this.CreateEscapedIdentifier(expression.MethodName));
		}

		protected override void GenerateEventReferenceExpression(global::System.CodeDom.CodeEventReferenceExpression expression)
		{
			if (expression.TargetObject != null)
			{
				base.GenerateExpression(expression.TargetObject);
				base.Output.Write('.');
				if (expression.TargetObject is global::System.CodeDom.CodeThisReferenceExpression)
				{
					base.Output.Write(expression.EventName + "Event");
				}
				else
				{
					base.Output.Write(this.CreateEscapedIdentifier(expression.EventName));
				}
			}
			else
			{
				base.Output.Write(this.CreateEscapedIdentifier(expression.EventName + "Event"));
			}
		}

		protected override void GenerateDelegateInvokeExpression(global::System.CodeDom.CodeDelegateInvokeExpression expression)
		{
			global::System.CodeDom.CodeEventReferenceExpression codeEventReferenceExpression = expression.TargetObject as global::System.CodeDom.CodeEventReferenceExpression;
			if (codeEventReferenceExpression != null)
			{
				base.Output.Write("RaiseEvent ");
				if (codeEventReferenceExpression.TargetObject != null && !(codeEventReferenceExpression.TargetObject is global::System.CodeDom.CodeThisReferenceExpression))
				{
					base.GenerateExpression(codeEventReferenceExpression.TargetObject);
					base.Output.Write(".");
				}
				base.Output.Write(codeEventReferenceExpression.EventName);
			}
			else if (expression.TargetObject != null)
			{
				base.GenerateExpression(expression.TargetObject);
			}
			base.Output.Write('(');
			this.OutputExpressionList(expression.Parameters);
			base.Output.Write(')');
		}

		protected override void GenerateObjectCreateExpression(global::System.CodeDom.CodeObjectCreateExpression expression)
		{
			base.Output.Write("New ");
			this.OutputType(expression.CreateType);
			base.Output.Write('(');
			this.OutputExpressionList(expression.Parameters);
			base.Output.Write(')');
		}

		protected override void GenerateParameterDeclarationExpression(global::System.CodeDom.CodeParameterDeclarationExpression e)
		{
			this.OutputAttributes(e.CustomAttributes, null, VBCodeGenerator.LineHandling.InLine);
			this.OutputDirection(e.Direction);
			this.OutputTypeNamePair(e.Type, e.Name);
		}

		protected override void GeneratePrimitiveExpression(global::System.CodeDom.CodePrimitiveExpression e)
		{
			if (e.Value is char)
			{
				char c = (char)e.Value;
				int num = (int)c;
				base.Output.Write("Global.Microsoft.VisualBasic.ChrW(" + num.ToString(CultureInfo.InvariantCulture) + ")");
			}
			else if (e.Value is ushort)
			{
				ushort num2 = (ushort)e.Value;
				base.Output.Write(num2.ToString(CultureInfo.InvariantCulture));
				base.Output.Write("US");
			}
			else if (e.Value is uint)
			{
				uint num3 = (uint)e.Value;
				base.Output.Write(num3.ToString(CultureInfo.InvariantCulture));
				base.Output.Write("UI");
			}
			else if (e.Value is ulong)
			{
				ulong num4 = (ulong)e.Value;
				base.Output.Write(num4.ToString(CultureInfo.InvariantCulture));
				base.Output.Write("UL");
			}
			else if (e.Value is sbyte)
			{
				sbyte b = (sbyte)e.Value;
				base.Output.Write("CSByte(");
				base.Output.Write(b.ToString(CultureInfo.InvariantCulture));
				base.Output.Write(')');
			}
			else
			{
				base.GeneratePrimitiveExpression(e);
			}
		}

		protected override void GenerateSingleFloatValue(float s)
		{
			base.GenerateSingleFloatValue(s);
			base.Output.Write('!');
		}

		protected override void GeneratePropertyReferenceExpression(global::System.CodeDom.CodePropertyReferenceExpression expression)
		{
			if (expression.TargetObject != null)
			{
				this.GenerateMemberReferenceExpression(expression.TargetObject, expression.PropertyName);
			}
			else
			{
				base.Output.Write(this.CreateEscapedIdentifier(expression.PropertyName));
			}
		}

		protected override void GeneratePropertySetValueReferenceExpression(global::System.CodeDom.CodePropertySetValueReferenceExpression expression)
		{
			base.Output.Write("Value");
		}

		protected override void GenerateThisReferenceExpression(global::System.CodeDom.CodeThisReferenceExpression expression)
		{
			base.Output.Write("Me");
		}

		protected override void GenerateExpressionStatement(global::System.CodeDom.CodeExpressionStatement statement)
		{
			base.GenerateExpression(statement.Expression);
			base.Output.WriteLine();
		}

		protected override void GenerateIterationStatement(global::System.CodeDom.CodeIterationStatement statement)
		{
			TextWriter output = base.Output;
			base.GenerateStatement(statement.InitStatement);
			output.Write("Do While ");
			base.GenerateExpression(statement.TestExpression);
			output.WriteLine();
			base.Indent++;
			base.GenerateStatements(statement.Statements);
			base.GenerateStatement(statement.IncrementStatement);
			base.Indent--;
			output.WriteLine("Loop");
		}

		protected override void GenerateThrowExceptionStatement(global::System.CodeDom.CodeThrowExceptionStatement statement)
		{
			base.Output.Write("Throw");
			if (statement.ToThrow != null)
			{
				base.Output.Write(' ');
				base.GenerateExpression(statement.ToThrow);
			}
			base.Output.WriteLine();
		}

		protected override void GenerateComment(global::System.CodeDom.CodeComment comment)
		{
			TextWriter output = base.Output;
			string text;
			if (comment.DocComment)
			{
				text = "'''";
			}
			else
			{
				text = "'";
			}
			output.Write(text);
			string text2 = comment.Text;
			for (int i = 0; i < text2.Length; i++)
			{
				output.Write(text2[i]);
				if (text2[i] == '\r')
				{
					if (i >= text2.Length - 1 || text2[i + 1] != '\n')
					{
						output.Write(text);
					}
				}
				else if (text2[i] == '\n')
				{
					output.Write(text);
				}
			}
			output.WriteLine();
		}

		protected override void GenerateMethodReturnStatement(global::System.CodeDom.CodeMethodReturnStatement statement)
		{
			TextWriter output = base.Output;
			if (statement.Expression != null)
			{
				output.Write("Return ");
				base.GenerateExpression(statement.Expression);
				output.WriteLine();
			}
			else
			{
				output.WriteLine("Return");
			}
		}

		protected override void GenerateConditionStatement(global::System.CodeDom.CodeConditionStatement statement)
		{
			TextWriter output = base.Output;
			output.Write("If ");
			base.GenerateExpression(statement.Condition);
			output.WriteLine(" Then");
			base.Indent++;
			base.GenerateStatements(statement.TrueStatements);
			base.Indent--;
			global::System.CodeDom.CodeStatementCollection falseStatements = statement.FalseStatements;
			if (falseStatements.Count > 0)
			{
				output.WriteLine("Else");
				base.Indent++;
				base.GenerateStatements(falseStatements);
				base.Indent--;
			}
			else if (base.Options.ElseOnClosing)
			{
				output.WriteLine("Else");
			}
			output.WriteLine("End If");
		}

		protected override void GenerateTryCatchFinallyStatement(global::System.CodeDom.CodeTryCatchFinallyStatement statement)
		{
			TextWriter output = base.Output;
			output.WriteLine("Try ");
			base.Indent++;
			base.GenerateStatements(statement.TryStatements);
			base.Indent--;
			foreach (object obj in statement.CatchClauses)
			{
				global::System.CodeDom.CodeCatchClause codeCatchClause = (global::System.CodeDom.CodeCatchClause)obj;
				output.Write("Catch ");
				this.OutputTypeNamePair(codeCatchClause.CatchExceptionType, codeCatchClause.LocalName);
				output.WriteLine();
				base.Indent++;
				base.GenerateStatements(codeCatchClause.Statements);
				base.Indent--;
			}
			global::System.CodeDom.CodeStatementCollection finallyStatements = statement.FinallyStatements;
			if (finallyStatements.Count > 0)
			{
				output.WriteLine("Finally");
				base.Indent++;
				base.GenerateStatements(finallyStatements);
				base.Indent--;
			}
			output.WriteLine("End Try");
		}

		protected override void GenerateAssignStatement(global::System.CodeDom.CodeAssignStatement statement)
		{
			TextWriter output = base.Output;
			base.GenerateExpression(statement.Left);
			output.Write(" = ");
			base.GenerateExpression(statement.Right);
			output.WriteLine();
		}

		protected override void GenerateAttachEventStatement(global::System.CodeDom.CodeAttachEventStatement statement)
		{
			TextWriter output = base.Output;
			base.Output.Write("AddHandler ");
			if (statement.Event.TargetObject != null)
			{
				this.GenerateEventReferenceExpression(statement.Event);
			}
			else
			{
				base.Output.Write(this.CreateEscapedIdentifier(statement.Event.EventName));
			}
			base.Output.Write(", ");
			base.GenerateExpression(statement.Listener);
			output.WriteLine();
		}

		protected override void GenerateRemoveEventStatement(global::System.CodeDom.CodeRemoveEventStatement statement)
		{
			TextWriter output = base.Output;
			base.Output.Write("RemoveHandler ");
			if (statement.Event.TargetObject != null)
			{
				this.GenerateEventReferenceExpression(statement.Event);
			}
			else
			{
				base.Output.Write(this.CreateEscapedIdentifier(statement.Event.EventName));
			}
			base.Output.Write(", ");
			base.GenerateExpression(statement.Listener);
			output.WriteLine();
		}

		protected override void GenerateGotoStatement(global::System.CodeDom.CodeGotoStatement statement)
		{
			TextWriter output = base.Output;
			output.Write("goto ");
			output.Write(statement.Label);
			output.WriteLine();
		}

		protected override void GenerateLabeledStatement(global::System.CodeDom.CodeLabeledStatement statement)
		{
			TextWriter output = base.Output;
			base.Indent--;
			output.WriteLine(statement.Label + ":");
			base.Indent++;
			if (statement.Statement != null)
			{
				base.GenerateStatement(statement.Statement);
			}
		}

		protected override void GenerateTypeOfExpression(global::System.CodeDom.CodeTypeOfExpression e)
		{
			TextWriter output = base.Output;
			output.Write("GetType(");
			this.OutputType(e.Type);
			output.Write(")");
		}

		protected override void GenerateVariableDeclarationStatement(global::System.CodeDom.CodeVariableDeclarationStatement statement)
		{
			TextWriter output = base.Output;
			output.Write("Dim ");
			this.OutputTypeNamePair(statement.Type, statement.Name);
			global::System.CodeDom.CodeExpression initExpression = statement.InitExpression;
			if (initExpression != null)
			{
				output.Write(" = ");
				base.GenerateExpression(initExpression);
			}
			output.WriteLine();
		}

		protected override void GenerateLinePragmaStart(global::System.CodeDom.CodeLinePragma linePragma)
		{
			base.Output.WriteLine();
			base.Output.Write("#ExternalSource(\"");
			base.Output.Write(linePragma.FileName);
			base.Output.Write("\",");
			base.Output.Write(linePragma.LineNumber);
			base.Output.WriteLine(")");
			base.Output.WriteLine(string.Empty);
		}

		protected override void GenerateLinePragmaEnd(global::System.CodeDom.CodeLinePragma linePragma)
		{
			base.Output.WriteLine("#End ExternalSource");
		}

		protected override void GenerateEvent(global::System.CodeDom.CodeMemberEvent eventRef, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum)
			{
				return;
			}
			TextWriter output = base.Output;
			this.OutputAttributes(eventRef.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			this.OutputMemberAccessModifier(eventRef.Attributes);
			output.Write("Event ");
			this.OutputTypeNamePair(eventRef.Type, this.GetEventName(eventRef));
			if (eventRef.ImplementationTypes.Count > 0)
			{
				this.OutputImplementationTypes(eventRef.ImplementationTypes, eventRef.Name);
			}
			else if (eventRef.PrivateImplementationType != null)
			{
				output.Write(" Implements ");
				this.OutputType(eventRef.PrivateImplementationType);
				output.Write('.');
				output.Write(eventRef.Name);
			}
			output.WriteLine();
		}

		protected override void GenerateField(global::System.CodeDom.CodeMemberField field)
		{
			if (base.IsCurrentDelegate || base.IsCurrentInterface)
			{
				return;
			}
			TextWriter output = base.Output;
			this.OutputAttributes(field.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			if (base.IsCurrentEnum)
			{
				output.Write(field.Name);
			}
			else
			{
				global::System.CodeDom.MemberAttributes attributes = field.Attributes;
				this.OutputMemberAccessModifier(attributes);
				this.OutputVTableModifier(attributes);
				this.OutputFieldScopeModifier(attributes);
				this.OutputTypeNamePair(field.Type, field.Name);
			}
			global::System.CodeDom.CodeExpression initExpression = field.InitExpression;
			if (initExpression != null)
			{
				output.Write(" = ");
				base.GenerateExpression(initExpression);
			}
			output.WriteLine();
		}

		protected override void GenerateSnippetMember(global::System.CodeDom.CodeSnippetTypeMember member)
		{
			base.Output.Write(member.Text);
		}

		protected override void GenerateEntryPointMethod(global::System.CodeDom.CodeEntryPointMethod method, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			this.OutputAttributes(method.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			base.Output.WriteLine("Public Shared Sub Main()");
			base.Indent++;
			base.GenerateStatements(method.Statements);
			base.Indent--;
			base.Output.WriteLine("End Sub");
		}

		[global::System.MonoTODO("partially implemented")]
		protected override void GenerateMethod(global::System.CodeDom.CodeMemberMethod method, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum)
			{
				return;
			}
			bool flag = method.ReturnType.BaseType == typeof(void).FullName;
			TextWriter output = base.Output;
			this.OutputAttributes(method.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			global::System.CodeDom.MemberAttributes attributes = method.Attributes;
			if (!base.IsCurrentInterface)
			{
				if (method.PrivateImplementationType == null)
				{
					this.OutputMemberAccessModifier(attributes);
					if (this.IsOverloaded(method, declaration))
					{
						output.Write("Overloads ");
					}
				}
				this.OutputVTableModifier(attributes);
				this.OutputMemberScopeModifier(attributes);
			}
			else
			{
				this.OutputVTableModifier(attributes);
			}
			if (flag)
			{
				output.Write("Sub ");
			}
			else
			{
				output.Write("Function ");
			}
			output.Write(this.GetMethodName(method));
			this.OutputTypeParameters(method.TypeParameters);
			output.Write('(');
			this.OutputParameters(method.Parameters);
			output.Write(')');
			if (!flag)
			{
				output.Write(" As ");
				this.OutputAttributes(method.ReturnTypeCustomAttributes, null, VBCodeGenerator.LineHandling.InLine);
				this.OutputType(method.ReturnType);
			}
			if (method.ImplementationTypes.Count > 0)
			{
				this.OutputImplementationTypes(method.ImplementationTypes, method.Name);
			}
			else if (method.PrivateImplementationType != null)
			{
				output.Write(" Implements ");
				this.OutputType(method.PrivateImplementationType);
				output.Write('.');
				output.Write(method.Name);
			}
			output.WriteLine();
			if (!base.IsCurrentInterface && (attributes & global::System.CodeDom.MemberAttributes.ScopeMask) != global::System.CodeDom.MemberAttributes.Abstract)
			{
				base.Indent++;
				base.GenerateStatements(method.Statements);
				base.Indent--;
				if (flag)
				{
					output.WriteLine("End Sub");
				}
				else
				{
					output.WriteLine("End Function");
				}
			}
		}

		protected override void GenerateProperty(global::System.CodeDom.CodeMemberProperty property, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum)
			{
				return;
			}
			TextWriter output = base.Output;
			this.OutputAttributes(property.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			global::System.CodeDom.MemberAttributes attributes = property.Attributes;
			if (!base.IsCurrentInterface)
			{
				if (property.PrivateImplementationType == null)
				{
					this.OutputMemberAccessModifier(attributes);
					if (this.IsOverloaded(property, declaration))
					{
						output.Write("Overloads ");
					}
				}
				this.OutputVTableModifier(attributes);
				this.OutputMemberScopeModifier(attributes);
			}
			else
			{
				this.OutputVTableModifier(attributes);
			}
			if (string.Compare(this.GetPropertyName(property), "Item", true, CultureInfo.InvariantCulture) == 0 && property.Parameters.Count > 0)
			{
				output.Write("Default ");
			}
			if (property.HasGet && !property.HasSet)
			{
				output.Write("ReadOnly ");
			}
			if (property.HasSet && !property.HasGet)
			{
				output.Write("WriteOnly ");
			}
			output.Write("Property ");
			base.Output.Write(this.GetPropertyName(property));
			base.Output.Write('(');
			this.OutputParameters(property.Parameters);
			base.Output.Write(')');
			base.Output.Write(" As ");
			base.Output.Write(this.GetTypeOutput(property.Type));
			if (property.ImplementationTypes.Count > 0)
			{
				this.OutputImplementationTypes(property.ImplementationTypes, property.Name);
			}
			else if (property.PrivateImplementationType != null)
			{
				output.Write(" Implements ");
				this.OutputType(property.PrivateImplementationType);
				output.Write('.');
				output.Write(property.Name);
			}
			output.WriteLine();
			if (!base.IsCurrentInterface)
			{
				base.Indent++;
				if (property.HasGet)
				{
					output.WriteLine("Get");
					if (!VBCodeGenerator.IsAbstract(property.Attributes))
					{
						base.Indent++;
						base.GenerateStatements(property.GetStatements);
						base.Indent--;
						output.WriteLine("End Get");
					}
				}
				if (property.HasSet)
				{
					output.WriteLine("Set");
					if (!VBCodeGenerator.IsAbstract(property.Attributes))
					{
						base.Indent++;
						base.GenerateStatements(property.SetStatements);
						base.Indent--;
						output.WriteLine("End Set");
					}
				}
				base.Indent--;
				output.WriteLine("End Property");
			}
		}

		protected override void GenerateConstructor(global::System.CodeDom.CodeConstructor constructor, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum || base.IsCurrentInterface)
			{
				return;
			}
			this.OutputAttributes(constructor.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			this.OutputMemberAccessModifier(constructor.Attributes);
			base.Output.Write("Sub New(");
			this.OutputParameters(constructor.Parameters);
			base.Output.WriteLine(")");
			base.Indent++;
			global::System.CodeDom.CodeExpressionCollection codeExpressionCollection = constructor.ChainedConstructorArgs;
			if (codeExpressionCollection.Count > 0)
			{
				base.Output.Write("Me.New(");
				this.OutputExpressionList(codeExpressionCollection);
				base.Output.WriteLine(")");
			}
			else
			{
				codeExpressionCollection = constructor.BaseConstructorArgs;
				if (codeExpressionCollection.Count > 0)
				{
					base.Output.Write("MyBase.New(");
					this.OutputExpressionList(codeExpressionCollection);
					base.Output.WriteLine(")");
				}
				else if (base.IsCurrentClass)
				{
					base.Output.WriteLine("MyBase.New");
				}
			}
			base.GenerateStatements(constructor.Statements);
			base.Indent--;
			base.Output.WriteLine("End Sub");
		}

		protected override void GenerateTypeConstructor(global::System.CodeDom.CodeTypeConstructor constructor)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum || base.IsCurrentInterface)
			{
				return;
			}
			this.OutputAttributes(constructor.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			base.Output.WriteLine("Shared Sub New()");
			base.Indent++;
			base.GenerateStatements(constructor.Statements);
			base.Indent--;
			base.Output.WriteLine("End Sub");
		}

		[global::System.MonoTODO("partially implemented")]
		protected override void GenerateTypeStart(global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			TextWriter output = base.Output;
			this.OutputAttributes(declaration.CustomAttributes, null, VBCodeGenerator.LineHandling.ContinueLine);
			TypeAttributes typeAttributes = declaration.TypeAttributes;
			if (base.IsCurrentDelegate)
			{
				global::System.CodeDom.CodeTypeDelegate codeTypeDelegate = (global::System.CodeDom.CodeTypeDelegate)declaration;
				if ((typeAttributes & TypeAttributes.VisibilityMask) == TypeAttributes.Public)
				{
					output.Write("Public ");
				}
				bool flag = codeTypeDelegate.ReturnType.BaseType == typeof(void).FullName;
				if (flag)
				{
					output.Write("Delegate Sub ");
				}
				else
				{
					output.Write("Delegate Function ");
				}
				output.Write(this.CreateEscapedIdentifier(codeTypeDelegate.Name));
				this.OutputTypeParameters(codeTypeDelegate.TypeParameters);
				output.Write("(");
				this.OutputParameters(codeTypeDelegate.Parameters);
				base.Output.Write(")");
				if (!flag)
				{
					base.Output.Write(" As ");
					this.OutputType(codeTypeDelegate.ReturnType);
				}
				base.Output.WriteLine(string.Empty);
			}
			else
			{
				this.OutputTypeAttributes(declaration);
				output.Write(this.CreateEscapedIdentifier(declaration.Name));
				this.OutputTypeParameters(declaration.TypeParameters);
				if (base.IsCurrentEnum)
				{
					if (declaration.BaseTypes.Count > 0)
					{
						output.Write(" As ");
						this.OutputType(declaration.BaseTypes[0]);
					}
					output.WriteLine();
					base.Indent++;
				}
				else
				{
					base.Indent++;
					bool flag2 = true;
					bool flag3 = true;
					for (int i = 0; i < declaration.BaseTypes.Count; i++)
					{
						global::System.CodeDom.CodeTypeReference codeTypeReference = declaration.BaseTypes[i];
						if (flag2 && !declaration.IsStruct && !codeTypeReference.IsInterface)
						{
							output.WriteLine();
							output.Write("Inherits ");
							flag2 = false;
						}
						else if (!declaration.IsInterface && flag3)
						{
							output.WriteLine();
							output.Write("Implements ");
							flag3 = false;
						}
						else
						{
							output.Write(", ");
						}
						this.OutputType(codeTypeReference);
					}
					output.WriteLine();
				}
			}
		}

		protected override void GenerateTypeEnd(global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate)
			{
				return;
			}
			string text = string.Empty;
			base.Indent--;
			if (declaration.IsStruct)
			{
				text = "End Structure";
			}
			if (declaration.IsInterface)
			{
				text = "End Interface";
			}
			if (declaration.IsEnum)
			{
				text = "End Enum";
			}
			if (declaration.IsClass)
			{
				text = "End Class";
			}
			base.Output.WriteLine(text);
		}

		protected override void GenerateNamespace(global::System.CodeDom.CodeNamespace ns)
		{
			base.GenerateNamespaceImports(ns);
			base.Output.WriteLine();
			this.GenerateCommentStatements(ns.Comments);
			this.GenerateNamespaceStart(ns);
			base.GenerateTypes(ns);
			this.GenerateNamespaceEnd(ns);
		}

		protected override void GenerateNamespaceStart(global::System.CodeDom.CodeNamespace ns)
		{
			TextWriter output = base.Output;
			string name = ns.Name;
			if (name != null && name != string.Empty)
			{
				output.Write("Namespace ");
				output.WriteLine(name);
				base.Indent++;
			}
		}

		protected override void GenerateNamespaceEnd(global::System.CodeDom.CodeNamespace ns)
		{
			string name = ns.Name;
			if (name != null && name != string.Empty)
			{
				base.Indent--;
				base.Output.WriteLine("End Namespace");
			}
		}

		protected override void GenerateNamespaceImport(global::System.CodeDom.CodeNamespaceImport import)
		{
			TextWriter output = base.Output;
			output.Write("Imports ");
			output.Write(import.Namespace);
			output.WriteLine();
		}

		protected override void GenerateAttributeDeclarationsStart(global::System.CodeDom.CodeAttributeDeclarationCollection attributes)
		{
			base.Output.Write('<');
		}

		protected override void GenerateAttributeDeclarationsEnd(global::System.CodeDom.CodeAttributeDeclarationCollection attributes)
		{
			base.Output.Write(">");
		}

		private void OutputAttributes(global::System.CodeDom.CodeAttributeDeclarationCollection attributes, string prefix, VBCodeGenerator.LineHandling lineHandling)
		{
			if (attributes.Count == 0)
			{
				return;
			}
			this.GenerateAttributeDeclarationsStart(attributes);
			IEnumerator enumerator = attributes.GetEnumerator();
			if (enumerator.MoveNext())
			{
				global::System.CodeDom.CodeAttributeDeclaration codeAttributeDeclaration = (global::System.CodeDom.CodeAttributeDeclaration)enumerator.Current;
				if (prefix != null)
				{
					base.Output.Write(prefix);
				}
				this.OutputAttributeDeclaration(codeAttributeDeclaration);
				while (enumerator.MoveNext())
				{
					base.Output.Write(", ");
					if (lineHandling != VBCodeGenerator.LineHandling.InLine)
					{
						this.ContinueOnNewLine(string.Empty);
						base.Output.Write(" ");
					}
					codeAttributeDeclaration = (global::System.CodeDom.CodeAttributeDeclaration)enumerator.Current;
					if (prefix != null)
					{
						base.Output.Write(prefix);
					}
					this.OutputAttributeDeclaration(codeAttributeDeclaration);
				}
			}
			this.GenerateAttributeDeclarationsEnd(attributes);
			base.Output.Write(" ");
			if (lineHandling != VBCodeGenerator.LineHandling.ContinueLine)
			{
				if (lineHandling == VBCodeGenerator.LineHandling.NewLine)
				{
					base.Output.WriteLine();
				}
			}
			else
			{
				this.ContinueOnNewLine(string.Empty);
			}
		}

		protected override void OutputAttributeArgument(global::System.CodeDom.CodeAttributeArgument argument)
		{
			string name = argument.Name;
			if (name != null && name.Length > 0)
			{
				base.Output.Write(name);
				base.Output.Write(":=");
			}
			base.GenerateExpression(argument.Value);
		}

		private void OutputAttributeDeclaration(global::System.CodeDom.CodeAttributeDeclaration attribute)
		{
			base.Output.Write(attribute.Name.Replace('+', '.'));
			base.Output.Write('(');
			IEnumerator enumerator = attribute.Arguments.GetEnumerator();
			if (enumerator.MoveNext())
			{
				global::System.CodeDom.CodeAttributeArgument codeAttributeArgument = (global::System.CodeDom.CodeAttributeArgument)enumerator.Current;
				this.OutputAttributeArgument(codeAttributeArgument);
				while (enumerator.MoveNext())
				{
					base.Output.Write(", ");
					codeAttributeArgument = (global::System.CodeDom.CodeAttributeArgument)enumerator.Current;
					this.OutputAttributeArgument(codeAttributeArgument);
				}
			}
			base.Output.Write(')');
		}

		protected override void OutputDirection(global::System.CodeDom.FieldDirection direction)
		{
			switch (direction)
			{
			case global::System.CodeDom.FieldDirection.In:
				base.Output.Write("ByVal ");
				break;
			case global::System.CodeDom.FieldDirection.Out:
			case global::System.CodeDom.FieldDirection.Ref:
				base.Output.Write("ByRef ");
				break;
			}
		}

		protected override void OutputFieldScopeModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			switch (attributes & global::System.CodeDom.MemberAttributes.ScopeMask)
			{
			case global::System.CodeDom.MemberAttributes.Static:
				base.Output.Write("Shared ");
				break;
			case global::System.CodeDom.MemberAttributes.Const:
				base.Output.Write("Const ");
				break;
			}
		}

		private void OutputImplementationTypes(global::System.CodeDom.CodeTypeReferenceCollection implementationTypes, string member)
		{
			IEnumerator enumerator = implementationTypes.GetEnumerator();
			if (enumerator.MoveNext())
			{
				base.Output.Write(" Implements ");
				global::System.CodeDom.CodeTypeReference codeTypeReference = (global::System.CodeDom.CodeTypeReference)enumerator.Current;
				this.OutputType(codeTypeReference);
				base.Output.Write('.');
				this.OutputIdentifier(member);
				while (enumerator.MoveNext())
				{
					base.Output.Write(" , ");
					codeTypeReference = (global::System.CodeDom.CodeTypeReference)enumerator.Current;
					this.OutputType(codeTypeReference);
					base.Output.Write('.');
					this.OutputIdentifier(member);
				}
			}
		}

		protected override void OutputMemberAccessModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			global::System.CodeDom.MemberAttributes memberAttributes = attributes & global::System.CodeDom.MemberAttributes.AccessMask;
			if (memberAttributes != global::System.CodeDom.MemberAttributes.Assembly && memberAttributes != global::System.CodeDom.MemberAttributes.FamilyAndAssembly)
			{
				if (memberAttributes != global::System.CodeDom.MemberAttributes.Family)
				{
					if (memberAttributes != global::System.CodeDom.MemberAttributes.FamilyOrAssembly)
					{
						if (memberAttributes != global::System.CodeDom.MemberAttributes.Private)
						{
							if (memberAttributes == global::System.CodeDom.MemberAttributes.Public)
							{
								base.Output.Write("Public ");
							}
						}
						else
						{
							base.Output.Write("Private ");
						}
					}
					else
					{
						base.Output.Write("Protected Friend ");
					}
				}
				else
				{
					base.Output.Write("Protected ");
				}
			}
			else
			{
				base.Output.Write("Friend ");
			}
		}

		private void OutputVTableModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			if ((attributes & global::System.CodeDom.MemberAttributes.VTableMask) == global::System.CodeDom.MemberAttributes.New)
			{
				base.Output.Write("Shadows ");
			}
		}

		protected override void OutputMemberScopeModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			global::System.CodeDom.MemberAttributes memberAttributes = attributes & global::System.CodeDom.MemberAttributes.ScopeMask;
			switch (memberAttributes)
			{
			case global::System.CodeDom.MemberAttributes.Abstract:
				base.Output.Write("MustOverride ");
				break;
			case global::System.CodeDom.MemberAttributes.Final:
				break;
			case global::System.CodeDom.MemberAttributes.Static:
				base.Output.Write("Shared ");
				break;
			case global::System.CodeDom.MemberAttributes.Override:
				base.Output.Write("Overrides ");
				break;
			default:
				if (memberAttributes != global::System.CodeDom.MemberAttributes.Overloaded)
				{
					global::System.CodeDom.MemberAttributes memberAttributes2 = attributes & global::System.CodeDom.MemberAttributes.AccessMask;
					if (memberAttributes2 == global::System.CodeDom.MemberAttributes.Public || memberAttributes2 == global::System.CodeDom.MemberAttributes.Family || memberAttributes2 == global::System.CodeDom.MemberAttributes.Assembly)
					{
						base.Output.Write("Overridable ");
					}
				}
				else
				{
					base.Output.Write("Overloads ");
					global::System.CodeDom.MemberAttributes memberAttributes3 = attributes & global::System.CodeDom.MemberAttributes.AccessMask;
					if (memberAttributes3 == global::System.CodeDom.MemberAttributes.Public || memberAttributes3 == global::System.CodeDom.MemberAttributes.Family)
					{
						base.Output.Write("Overridable ");
					}
				}
				break;
			}
		}

		protected override void OutputOperator(global::System.CodeDom.CodeBinaryOperatorType op)
		{
			switch (op)
			{
			case global::System.CodeDom.CodeBinaryOperatorType.Add:
				base.Output.Write("+");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.Subtract:
				base.Output.Write("-");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.Multiply:
				base.Output.Write("*");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.Divide:
				base.Output.Write("/");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.Modulus:
				base.Output.Write("Mod");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.Assign:
				base.Output.Write("=");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.IdentityInequality:
				base.Output.Write("<>");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.IdentityEquality:
				base.Output.Write("Is");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.ValueEquality:
				base.Output.Write("=");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.BitwiseOr:
				base.Output.Write("Or");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.BitwiseAnd:
				base.Output.Write("And");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.BooleanOr:
				base.Output.Write("OrElse");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.BooleanAnd:
				base.Output.Write("AndAlso");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.LessThan:
				base.Output.Write("<");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.LessThanOrEqual:
				base.Output.Write("<=");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.GreaterThan:
				base.Output.Write(">");
				break;
			case global::System.CodeDom.CodeBinaryOperatorType.GreaterThanOrEqual:
				base.Output.Write(">=");
				break;
			}
		}

		private void OutputTypeAttributes(global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			TextWriter output = base.Output;
			TypeAttributes typeAttributes = declaration.TypeAttributes;
			if (declaration.IsPartial)
			{
				output.Write("Partial ");
			}
			switch (typeAttributes & TypeAttributes.VisibilityMask)
			{
			case TypeAttributes.NotPublic:
			case TypeAttributes.NestedAssembly:
			case TypeAttributes.NestedFamANDAssem:
				output.Write("Friend ");
				break;
			case TypeAttributes.Public:
			case TypeAttributes.NestedPublic:
				output.Write("Public ");
				break;
			case TypeAttributes.NestedPrivate:
				output.Write("Private ");
				break;
			case TypeAttributes.NestedFamily:
				output.Write("Protected ");
				break;
			case TypeAttributes.VisibilityMask:
				output.Write("Protected Friend ");
				break;
			}
			if (declaration.IsStruct)
			{
				output.Write("Structure ");
			}
			else if (declaration.IsEnum)
			{
				output.Write("Enum ");
			}
			else if ((typeAttributes & TypeAttributes.ClassSemanticsMask) != TypeAttributes.NotPublic)
			{
				output.Write("Interface ");
			}
			else
			{
				if ((typeAttributes & TypeAttributes.Sealed) != TypeAttributes.NotPublic)
				{
					output.Write("NotInheritable ");
				}
				if ((typeAttributes & TypeAttributes.Abstract) != TypeAttributes.NotPublic)
				{
					output.Write("MustInherit ");
				}
				output.Write("Class ");
			}
		}

		private void OutputTypeParameters(global::System.CodeDom.CodeTypeParameterCollection parameters)
		{
			int count = parameters.Count;
			if (count == 0)
			{
				return;
			}
			base.Output.Write("(Of ");
			for (int i = 0; i < count; i++)
			{
				if (i > 0)
				{
					base.Output.Write(", ");
				}
				global::System.CodeDom.CodeTypeParameter codeTypeParameter = parameters[i];
				base.Output.Write(codeTypeParameter.Name);
				this.OutputTypeParameterConstraints(codeTypeParameter);
			}
			base.Output.Write(')');
		}

		private void OutputTypeParameterConstraints(global::System.CodeDom.CodeTypeParameter parameter)
		{
			int num = parameter.Constraints.Count + ((!parameter.HasConstructorConstraint) ? 0 : 1);
			if (num == 0)
			{
				return;
			}
			base.Output.Write(" As ");
			if (num > 1)
			{
				base.Output.Write(" {");
			}
			for (int i = 0; i < parameter.Constraints.Count; i++)
			{
				if (i > 0)
				{
					base.Output.Write(", ");
				}
				this.OutputType(parameter.Constraints[i]);
			}
			if (parameter.HasConstructorConstraint)
			{
				if (num > 1)
				{
					base.Output.Write(", ");
				}
				base.Output.Write("New");
			}
			if (num > 1)
			{
				base.Output.Write("}");
			}
		}

		protected override void OutputTypeNamePair(global::System.CodeDom.CodeTypeReference typeRef, string name)
		{
			if (name.Length == 0)
			{
				name = "__exception";
			}
			base.Output.Write(this.CreateEscapedIdentifier(name) + " As " + this.GetTypeOutput(typeRef));
		}

		protected override void OutputType(global::System.CodeDom.CodeTypeReference type)
		{
			base.Output.Write(this.GetTypeOutput(type));
		}

		protected override string QuoteSnippetString(string value)
		{
			StringBuilder stringBuilder = new StringBuilder(value.Length);
			stringBuilder.Append("\"");
			bool flag = true;
			for (int i = 0; i < value.Length; i++)
			{
				if (value[i] == '"')
				{
					if (!flag)
					{
						stringBuilder.Append("&\"");
						flag = true;
					}
					stringBuilder.Append(value[i]);
					stringBuilder.Append(value[i]);
				}
				else if (value[i] >= ' ')
				{
					if (!flag)
					{
						stringBuilder.Append("&\"");
						flag = true;
					}
					stringBuilder.Append(value[i]);
				}
				else
				{
					if (flag)
					{
						stringBuilder.Append("\"");
						flag = false;
					}
					stringBuilder.Append("&Microsoft.VisualBasic.ChrW(");
					stringBuilder.Append((int)value[i]);
					stringBuilder.Append(")");
				}
			}
			if (flag)
			{
				stringBuilder.Append("\"");
			}
			return stringBuilder.ToString();
		}

		private void GenerateMemberReferenceExpression(global::System.CodeDom.CodeExpression targetObject, string memberName)
		{
			base.GenerateExpression(targetObject);
			base.Output.Write('.');
			base.Output.Write(memberName);
		}

		protected override string CreateEscapedIdentifier(string value)
		{
			for (int i = 0; i < this.Keywords.Length; i++)
			{
				if (value.ToLower().Equals(this.Keywords[i].ToLower()))
				{
					return "[" + value + "]";
				}
			}
			return value;
		}

		protected override string CreateValidIdentifier(string value)
		{
			for (int i = 0; i < this.Keywords.Length; i++)
			{
				if (value.ToLower().Equals(this.Keywords[i].ToLower()))
				{
					return "_" + value;
				}
			}
			return value;
		}

		protected override string GetTypeOutput(global::System.CodeDom.CodeTypeReference type)
		{
			global::System.CodeDom.CodeTypeReference arrayElementType = type.ArrayElementType;
			string text;
			if (arrayElementType != null)
			{
				text = this.GetTypeOutput(arrayElementType);
			}
			else
			{
				string baseType = type.BaseType;
				switch (baseType)
				{
				case "System.DateTime":
					text = "Date";
					goto IL_0243;
				case "System.Decimal":
					text = "Decimal";
					goto IL_0243;
				case "System.Double":
					text = "Double";
					goto IL_0243;
				case "System.Single":
					text = "Single";
					goto IL_0243;
				case "System.Byte":
					text = "Byte";
					goto IL_0243;
				case "System.Int32":
					text = "Integer";
					goto IL_0243;
				case "System.Int64":
					text = "Long";
					goto IL_0243;
				case "System.Int16":
					text = "Short";
					goto IL_0243;
				case "System.Boolean":
					text = "Boolean";
					goto IL_0243;
				case "System.Char":
					text = "Char";
					goto IL_0243;
				case "System.String":
					text = "String";
					goto IL_0243;
				case "System.Object":
					text = "Object";
					goto IL_0243;
				case "System.SByte":
					text = "SByte";
					goto IL_0243;
				case "System.UInt16":
					text = "UShort";
					goto IL_0243;
				case "System.UInt32":
					text = "UInteger";
					goto IL_0243;
				case "System.UInt64":
					text = "ULong";
					goto IL_0243;
				}
				text = type.BaseType.Replace('+', '.');
				text = this.CreateEscapedIdentifier(text);
			}
			IL_0243:
			int i = type.ArrayRank;
			if (i > 0)
			{
				text += "(";
				for (i--; i > 0; i--)
				{
					text += ",";
				}
				text += ")";
			}
			return text;
		}

		protected override bool IsValidIdentifier(string identifier)
		{
			for (int i = 0; i < this.Keywords.Length; i++)
			{
				if (identifier.ToLower().Equals(this.Keywords[i].ToLower()))
				{
					return false;
				}
			}
			return true;
		}

		protected override bool Supports(global::System.CodeDom.Compiler.GeneratorSupport supports)
		{
			return true;
		}

		private bool IsOverloaded(global::System.CodeDom.CodeMemberProperty property, global::System.CodeDom.CodeTypeDeclaration type)
		{
			if ((property.Attributes & global::System.CodeDom.MemberAttributes.Overloaded) == global::System.CodeDom.MemberAttributes.Overloaded)
			{
				return true;
			}
			foreach (object obj in type.Members)
			{
				global::System.CodeDom.CodeTypeMember codeTypeMember = (global::System.CodeDom.CodeTypeMember)obj;
				global::System.CodeDom.CodeMemberProperty codeMemberProperty = codeTypeMember as global::System.CodeDom.CodeMemberProperty;
				if (codeMemberProperty != null)
				{
					if (codeMemberProperty != property && codeMemberProperty.Name == property.Name && codeMemberProperty.PrivateImplementationType == null)
					{
						return true;
					}
				}
			}
			return false;
		}

		private bool IsOverloaded(global::System.CodeDom.CodeMemberMethod method, global::System.CodeDom.CodeTypeDeclaration type)
		{
			if ((method.Attributes & global::System.CodeDom.MemberAttributes.Overloaded) == global::System.CodeDom.MemberAttributes.Overloaded)
			{
				return true;
			}
			foreach (object obj in type.Members)
			{
				global::System.CodeDom.CodeTypeMember codeTypeMember = (global::System.CodeDom.CodeTypeMember)obj;
				global::System.CodeDom.CodeMemberMethod codeMemberMethod = codeTypeMember as global::System.CodeDom.CodeMemberMethod;
				if (codeMemberMethod != null)
				{
					if (!(codeMemberMethod is global::System.CodeDom.CodeTypeConstructor) && !(codeMemberMethod is global::System.CodeDom.CodeConstructor) && codeMemberMethod != method && codeMemberMethod.Name == method.Name && codeMemberMethod.PrivateImplementationType == null)
					{
						return true;
					}
				}
			}
			return false;
		}

		private string GetEventName(global::System.CodeDom.CodeMemberEvent evt)
		{
			if (evt.PrivateImplementationType == null)
			{
				return evt.Name;
			}
			string text = evt.PrivateImplementationType.BaseType.Replace('.', '_');
			return text + "_" + evt.Name;
		}

		private string GetMethodName(global::System.CodeDom.CodeMemberMethod method)
		{
			if (method.PrivateImplementationType == null)
			{
				return method.Name;
			}
			string text = method.PrivateImplementationType.BaseType.Replace('.', '_');
			return text + "_" + method.Name;
		}

		private string GetPropertyName(global::System.CodeDom.CodeMemberProperty property)
		{
			if (property.PrivateImplementationType == null)
			{
				return property.Name;
			}
			string text = property.PrivateImplementationType.BaseType.Replace('.', '_');
			return text + "_" + property.Name;
		}

		private static bool IsAbstract(global::System.CodeDom.MemberAttributes attributes)
		{
			return (attributes & global::System.CodeDom.MemberAttributes.ScopeMask) == global::System.CodeDom.MemberAttributes.Abstract;
		}

		private string[] Keywords = new string[]
		{
			"AddHandler", "AddressOf", "Alias", "And", "AndAlso", "Ansi", "As", "Assembly", "Auto", "Boolean",
			"ByRef", "Byte", "ByVal", "Call", "Case", "Catch", "CBool", "CByte", "CChar", "CDate",
			"CDec", "CDbl", "Char", "CInt", "Class", "CLng", "CObj", "Const", "CShort", "CSng",
			"CStr", "CType", "Date", "Decimal", "Declare", "Default", "Delegate", "Dim", "DirectCast", "Do",
			"Double", "Each", "Else", "ElseIf", "End", "Enum", "Erase", "Error", "Event", "Exit",
			"False", "Finally", "For", "Friend", "Function", "Get", "GetType", "Global", "GoSub", "GoTo",
			"Handles", "If", "Implements", "Imports", "In", "Inherits", "Integer", "Interface", "Is", "Let",
			"Lib", "Like", "Long", "Loop", "Me", "Mod", "Module", "MustInherit", "MustOverride", "MyBase",
			"MyClass", "Namespace", "New", "Next", "Not", "Nothing", "NotInheritable", "NotOverridable", "Object", "On",
			"Option", "Optional", "Or", "OrElse", "Overloads", "Overridable", "Overrides", "ParamArray", "Partial", "Preserve",
			"Private", "Property", "Protected", "Public", "RaiseEvent", "ReadOnly", "ReDim", "REM", "RemoveHandler", "Resume",
			"Return", "Select", "Set", "Shadows", "Shared", "Short", "Single", "Static", "Step", "Stop",
			"String", "Structure", "Sub", "SyncLock", "Then", "Throw", "To", "True", "Try", "TypeOf",
			"Unicode", "Until", "Variant", "When", "While", "With", "WithEvents", "WriteOnly", "Xor"
		};

		private enum LineHandling
		{
			InLine,
			ContinueLine,
			NewLine
		}
	}
}
