using System;

namespace System.Runtime.Diagnostics
{
	internal enum EventLogEventId : uint
	{
		FailedToSetupTracing = 3221291108U,
		FailedToInitializeTraceSource,
		FailFast,
		FailFastException,
		FailedToTraceEvent,
		FailedToTraceEventWithException,
		InvariantAssertionFailed,
		PiiLoggingOn,
		PiiLoggingNotAllowed,
		WebHostUnhandledException = 3221356545U,
		WebHostHttpError,
		WebHostFailedToProcessRequest,
		WebHostFailedToListen,
		FailedToLogMessage,
		RemovedBadFilter,
		FailedToCreateMessageLoggingTraceSource,
		MessageLoggingOn,
		MessageLoggingOff,
		FailedToLoadPerformanceCounter,
		FailedToRemovePerformanceCounter,
		WmiGetObjectFailed,
		WmiPutInstanceFailed,
		WmiDeleteInstanceFailed,
		WmiCreateInstanceFailed,
		WmiExecQueryFailed,
		WmiExecMethodFailed,
		WmiRegistrationFailed,
		WmiUnregistrationFailed,
		WmiAdminTypeMismatch,
		WmiPropertyMissing,
		ComPlusServiceHostStartingServiceError,
		ComPlusDllHostInitializerStartingError,
		ComPlusTLBImportError,
		ComPlusInvokingMethodFailed,
		ComPlusInstanceCreationError,
		ComPlusInvokingMethodFailedMismatchedTransactions,
		WebHostNotLoggingInsufficientMemoryExceptionsOnActivationForNextTimeInterval = 2147614748U,
		UnhandledStateMachineExceptionRecordDescription = 3221422081U,
		FatalUnexpectedStateMachineEvent,
		ParticipantRecoveryLogEntryCorrupt,
		CoordinatorRecoveryLogEntryCorrupt,
		CoordinatorRecoveryLogEntryCreationFailure,
		ParticipantRecoveryLogEntryCreationFailure,
		ProtocolInitializationFailure,
		ProtocolStartFailure,
		ProtocolRecoveryBeginningFailure,
		ProtocolRecoveryCompleteFailure,
		TransactionBridgeRecoveryFailure,
		ProtocolStopFailure,
		NonFatalUnexpectedStateMachineEvent,
		PerformanceCounterInitializationFailure,
		ProtocolRecoveryComplete,
		ProtocolStopped,
		ThumbPrintNotFound,
		ThumbPrintNotValidated,
		SslNoPrivateKey,
		SslNoAccessiblePrivateKey,
		MissingNecessaryKeyUsage,
		MissingNecessaryEnhancedKeyUsage,
		StartErrorPublish = 3221487617U,
		BindingError,
		LAFailedToListenForApp,
		UnknownListenerAdapterError,
		WasDisconnected,
		WasConnectionTimedout,
		ServiceStartFailed,
		MessageQueueDuplicatedSocketLeak,
		MessageQueueDuplicatedPipeLeak,
		SharingUnhandledException,
		ServiceAuthorizationSuccess = 1074135041U,
		ServiceAuthorizationFailure = 3221618690U,
		MessageAuthenticationSuccess = 1074135043U,
		MessageAuthenticationFailure = 3221618692U,
		SecurityNegotiationSuccess = 1074135045U,
		SecurityNegotiationFailure = 3221618694U,
		TransportAuthenticationSuccess = 1074135047U,
		TransportAuthenticationFailure = 3221618696U,
		ImpersonationSuccess = 1074135049U,
		ImpersonationFailure = 3221618698U
	}
}
