using System;

namespace System.Xml
{
	internal enum XmlBinaryNodeType
	{
		EndElement = 1,
		Comment,
		Array,
		MinAttribute,
		ShortAttribute = 4,
		Attribute,
		ShortDictionaryAttribute,
		DictionaryAttribute,
		ShortXmlnsAttribute,
		XmlnsAttribute,
		ShortDictionaryXmlnsAttribute,
		DictionaryXmlnsAttribute,
		PrefixDictionaryAttributeA,
		PrefixDictionaryAttributeB,
		PrefixDictionaryAttributeC,
		PrefixDictionaryAttributeD,
		PrefixDictionaryAttributeE,
		PrefixDictionaryAttributeF,
		PrefixDictionaryAttributeG,
		PrefixDictionaryAttributeH,
		PrefixDictionaryAttributeI,
		PrefixDictionaryAttributeJ,
		PrefixDictionaryAttributeK,
		PrefixDictionaryAttributeL,
		PrefixDictionaryAttributeM,
		PrefixDictionaryAttributeN,
		PrefixDictionaryAttributeO,
		PrefixDictionaryAttributeP,
		PrefixDictionaryAttributeQ,
		PrefixDictionaryAttributeR,
		PrefixDictionaryAttributeS,
		PrefixDictionaryAttributeT,
		PrefixDictionaryAttributeU,
		PrefixDictionaryAttributeV,
		PrefixDictionaryAttributeW,
		PrefixDictionaryAttributeX,
		PrefixDictionaryAttributeY,
		PrefixDictionaryAttributeZ,
		PrefixAttributeA,
		PrefixAttributeB,
		PrefixAttributeC,
		PrefixAttributeD,
		PrefixAttributeE,
		PrefixAttributeF,
		PrefixAttributeG,
		PrefixAttributeH,
		PrefixAttributeI,
		PrefixAttributeJ,
		PrefixAttributeK,
		PrefixAttributeL,
		PrefixAttributeM,
		PrefixAttributeN,
		PrefixAttributeO,
		PrefixAttributeP,
		PrefixAttributeQ,
		PrefixAttributeR,
		PrefixAttributeS,
		PrefixAttributeT,
		PrefixAttributeU,
		PrefixAttributeV,
		PrefixAttributeW,
		PrefixAttributeX,
		PrefixAttributeY,
		PrefixAttributeZ,
		MaxAttribute = 63,
		MinElement,
		ShortElement = 64,
		Element,
		ShortDictionaryElement,
		DictionaryElement,
		PrefixDictionaryElementA,
		PrefixDictionaryElementB,
		PrefixDictionaryElementC,
		PrefixDictionaryElementD,
		PrefixDictionaryElementE,
		PrefixDictionaryElementF,
		PrefixDictionaryElementG,
		PrefixDictionaryElementH,
		PrefixDictionaryElementI,
		PrefixDictionaryElementJ,
		PrefixDictionaryElementK,
		PrefixDictionaryElementL,
		PrefixDictionaryElementM,
		PrefixDictionaryElementN,
		PrefixDictionaryElementO,
		PrefixDictionaryElementP,
		PrefixDictionaryElementQ,
		PrefixDictionaryElementR,
		PrefixDictionaryElementS,
		PrefixDictionaryElementT,
		PrefixDictionaryElementU,
		PrefixDictionaryElementV,
		PrefixDictionaryElementW,
		PrefixDictionaryElementX,
		PrefixDictionaryElementY,
		PrefixDictionaryElementZ,
		PrefixElementA,
		PrefixElementB,
		PrefixElementC,
		PrefixElementD,
		PrefixElementE,
		PrefixElementF,
		PrefixElementG,
		PrefixElementH,
		PrefixElementI,
		PrefixElementJ,
		PrefixElementK,
		PrefixElementL,
		PrefixElementM,
		PrefixElementN,
		PrefixElementO,
		PrefixElementP,
		PrefixElementQ,
		PrefixElementR,
		PrefixElementS,
		PrefixElementT,
		PrefixElementU,
		PrefixElementV,
		PrefixElementW,
		PrefixElementX,
		PrefixElementY,
		PrefixElementZ,
		MaxElement = 119,
		MinText = 128,
		ZeroText = 128,
		OneText = 130,
		FalseText = 132,
		TrueText = 134,
		Int8Text = 136,
		Int16Text = 138,
		Int32Text = 140,
		Int64Text = 142,
		FloatText = 144,
		DoubleText = 146,
		DecimalText = 148,
		DateTimeText = 150,
		Chars8Text = 152,
		Chars16Text = 154,
		Chars32Text = 156,
		Bytes8Text = 158,
		Bytes16Text = 160,
		Bytes32Text = 162,
		StartListText = 164,
		EndListText = 166,
		EmptyText = 168,
		DictionaryText = 170,
		UniqueIdText = 172,
		TimeSpanText = 174,
		GuidText = 176,
		UInt64Text = 178,
		BoolText = 180,
		UnicodeChars8Text = 182,
		UnicodeChars16Text = 184,
		UnicodeChars32Text = 186,
		QNameDictionaryText = 188,
		ZeroTextWithEndElement = 129,
		OneTextWithEndElement = 131,
		FalseTextWithEndElement = 133,
		TrueTextWithEndElement = 135,
		Int8TextWithEndElement = 137,
		Int16TextWithEndElement = 139,
		Int32TextWithEndElement = 141,
		Int64TextWithEndElement = 143,
		FloatTextWithEndElement = 145,
		DoubleTextWithEndElement = 147,
		DecimalTextWithEndElement = 149,
		DateTimeTextWithEndElement = 151,
		Chars8TextWithEndElement = 153,
		Chars16TextWithEndElement = 155,
		Chars32TextWithEndElement = 157,
		Bytes8TextWithEndElement = 159,
		Bytes16TextWithEndElement = 161,
		Bytes32TextWithEndElement = 163,
		StartListTextWithEndElement = 165,
		EndListTextWithEndElement = 167,
		EmptyTextWithEndElement = 169,
		DictionaryTextWithEndElement = 171,
		UniqueIdTextWithEndElement = 173,
		TimeSpanTextWithEndElement = 175,
		GuidTextWithEndElement = 177,
		UInt64TextWithEndElement = 179,
		BoolTextWithEndElement = 181,
		UnicodeChars8TextWithEndElement = 183,
		UnicodeChars16TextWithEndElement = 185,
		UnicodeChars32TextWithEndElement = 187,
		QNameDictionaryTextWithEndElement = 189,
		MaxText = 189
	}
}
