using System;

namespace UnityEngine.TextCore
{
	internal enum Unicode : uint
	{
		SPACE = 32U,
		DOUBLE_QUOTE = 34U,
		NUMBER_SIGN,
		PERCENTAGE = 37U,
		PLUS = 43U,
		MINUS = 45U,
		PERIOD,
		HYPHEN_MINUS = 45U,
		SOFT_HYPHEN = 173U,
		HYPHEN = 8208U,
		NON_BREAKING_HYPHEN,
		ZERO_WIDTH_SPACE = 8203U,
		RIGHT_SINGLE_QUOTATION = 8217U,
		APOSTROPHE = 39U,
		WORD_JOINER = 8288U
	}
}
