using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("0.10.5501.27380")]
[assembly: AssemblyProduct("TiledSharp")]
[assembly: AssemblyInformationalVersion("0.10.2.0")]
[assembly: AssemblyDescription("C# library for parsing and importing TMX and TSX files generated by Tiled, a\r\ntile map generation tool")]
[assembly: AssemblyCopyright("Copyright 2012-2014 Marshall Ward")]
[assembly: AssemblyCompany("Marshall Ward")]
[assembly: AssemblyTitle("TiledSharp")]
