using System;

namespace System.Net.NetworkInformation
{
	internal enum IcmpV4Type
	{
		ICMP4_ECHO_REPLY,
		ICMP4_DST_UNREACH = 3,
		ICMP4_SOURCE_QUENCH,
		ICMP4_TIME_EXCEEDED = 11,
		ICMP4_PARAM_PROB,
		ICMP4_REDIRECT = 5,
		ICMP4_ECHO_REQUEST = 8,
		ICMP4_ROUTER_ADVERT,
		ICMP4_ROUTER_SOLICIT,
		ICMP4_TIMESTAMP_REQUEST = 13,
		ICMP4_TIMESTAMP_REPLY,
		ICMP4_MASK_REQUEST = 17,
		ICMP4_MASK_REPLY
	}
}
