using System;

namespace System.Net.Security
{
	internal enum SecurityBufferType
	{
		SECBUFFER_EMPTY,
		SECBUFFER_DATA,
		SECBUFFER_TOKEN,
		SECBUFFER_PKG_PARAMS,
		SECBUFFER_MISSING,
		SECBUFFER_EXTRA,
		SECBUFFER_STREAM_TRAILER,
		SECBUFFER_STREAM_HEADER,
		SECBUFFER_PADDING = 9,
		SECBUFFER_STREAM,
		SECBUFFER_CHANNEL_BINDINGS = 14,
		SECBUFFER_TARGET_HOST = 16,
		SECBUFFER_ALERT,
		SECBUFFER_APPLICATION_PROTOCOLS,
		SECBUFFER_READONLY = -2147483648,
		SECBUFFER_READONLY_WITH_CHECKSUM = 268435456
	}
}
