using System;

namespace System.Drawing
{
	internal enum GetSysColorIndex
	{
		COLOR_SCROLLBAR,
		COLOR_BACKGROUND,
		COLOR_ACTIVECAPTION,
		COLOR_INACTIVECAPTION,
		COLOR_MENU,
		COLOR_WINDOW,
		COLOR_WINDOWFRAME,
		COLOR_MENUTEXT,
		COLOR_WINDOWTEXT,
		COLOR_CAPTIONTEXT,
		COLOR_ACTIVEBORDER,
		COLOR_INACTIVEBORDER,
		COLOR_APPWORKSPACE,
		COLOR_HIGHLIGHT,
		COLOR_HIGHLIGHTTEXT,
		COLOR_BTNFACE,
		COLOR_BTNSHADOW,
		COLOR_GRAYTEXT,
		COLOR_BTNTEXT,
		COLOR_INACTIVECAPTIONTEXT,
		COLOR_BTNHIGHLIGHT,
		COLOR_3DDKSHADOW,
		COLOR_3DLIGHT,
		COLOR_INFOTEXT,
		COLOR_INFOBK,
		COLOR_HOTLIGHT = 26,
		COLOR_GRADIENTACTIVECAPTION,
		COLOR_GRADIENTINACTIVECAPTION,
		COLOR_MENUHIGHLIGHT,
		COLOR_MENUBAR,
		COLOR_DESKTOP = 1,
		COLOR_3DFACE = 16,
		COLOR_3DSHADOW = 16,
		COLOR_3DHIGHLIGHT = 20,
		COLOR_3DHILIGHT = 20,
		COLOR_BTNHILIGHT = 20,
		COLOR_MAXVALUE = 30
	}
}
