using System;

public enum ObjectLayer
{
	Minion,
	Building,
	Backwall,
	Pickupables,
	Canvases,
	Plants,
	FillPlacer,
	DigPlacer,
	MopPlacer,
	FoundationTile,
	PlasticTile,
	ReplacementTile,
	GasConduit,
	GasConduitTile,
	ReplacementGasConduit,
	GasConduitConnection,
	LiquidConduit,
	LiquidConduitTile,
	ReplacementLiquidConduit,
	LiquidConduitConnection,
	Wire,
	WireTile,
	ReplacementWire,
	WireConnectors,
	LogicGates,
	LogicWires,
	LogicWiresTiling,
	TravelTube,
	TravelTubeTile,
	ReplacementTravelTube,
	TravelTubeConnection,
	AttachableBuilding,
	NumLayers
}
