using System;

namespace Microsoft.SqlServer.Server
{
	internal enum EMDEventType
	{
		x_eet_Invalid,
		x_eet_Insert,
		x_eet_Update,
		x_eet_Delete,
		x_eet_Create_Table = 21,
		x_eet_Alter_Table,
		x_eet_Drop_Table,
		x_eet_Create_Index,
		x_eet_Alter_Index,
		x_eet_Drop_Index,
		x_eet_Create_Stats,
		x_eet_Update_Stats,
		x_eet_Drop_Stats,
		x_eet_Create_Secexpr = 31,
		x_eet_Drop_Secexpr = 33,
		x_eet_Create_Synonym,
		x_eet_Drop_Synonym = 36,
		x_eet_Create_View = 41,
		x_eet_Alter_View,
		x_eet_Drop_View,
		x_eet_Create_Procedure = 51,
		x_eet_Alter_Procedure,
		x_eet_Drop_Procedure,
		x_eet_Create_Function = 61,
		x_eet_Alter_Function,
		x_eet_Drop_Function,
		x_eet_Create_Trigger = 71,
		x_eet_Alter_Trigger,
		x_eet_Drop_Trigger,
		x_eet_Create_Event_Notification,
		x_eet_Drop_Event_Notification = 76,
		x_eet_Create_Type = 91,
		x_eet_Drop_Type = 93,
		x_eet_Create_Assembly = 101,
		x_eet_Alter_Assembly,
		x_eet_Drop_Assembly,
		x_eet_Create_User = 131,
		x_eet_Alter_User,
		x_eet_Drop_User,
		x_eet_Create_Role,
		x_eet_Alter_Role,
		x_eet_Drop_Role,
		x_eet_Create_AppRole,
		x_eet_Alter_AppRole,
		x_eet_Drop_AppRole,
		x_eet_Create_Schema = 141,
		x_eet_Alter_Schema,
		x_eet_Drop_Schema,
		x_eet_Create_Login,
		x_eet_Alter_Login,
		x_eet_Drop_Login,
		x_eet_Create_MsgType = 151,
		x_eet_Alter_MsgType,
		x_eet_Drop_MsgType,
		x_eet_Create_Contract,
		x_eet_Alter_Contract,
		x_eet_Drop_Contract,
		x_eet_Create_Queue,
		x_eet_Alter_Queue,
		x_eet_Drop_Queue,
		x_eet_Create_Service = 161,
		x_eet_Alter_Service,
		x_eet_Drop_Service,
		x_eet_Create_Route,
		x_eet_Alter_Route,
		x_eet_Drop_Route,
		x_eet_Grant_Statement,
		x_eet_Deny_Statement,
		x_eet_Revoke_Statement,
		x_eet_Grant_Object,
		x_eet_Deny_Object,
		x_eet_Revoke_Object,
		x_eet_Activation,
		x_eet_Create_Binding,
		x_eet_Alter_Binding,
		x_eet_Drop_Binding,
		x_eet_Create_XmlSchema,
		x_eet_Alter_XmlSchema,
		x_eet_Drop_XmlSchema,
		x_eet_Create_HttpEndpoint = 181,
		x_eet_Alter_HttpEndpoint,
		x_eet_Drop_HttpEndpoint,
		x_eet_Create_Partition_Function = 191,
		x_eet_Alter_Partition_Function,
		x_eet_Drop_Partition_Function,
		x_eet_Create_Partition_Scheme,
		x_eet_Alter_Partition_Scheme,
		x_eet_Drop_Partition_Scheme,
		x_eet_Create_Database = 201,
		x_eet_Alter_Database,
		x_eet_Drop_Database,
		x_eet_Trace_Start = 1000,
		x_eet_Trace_End = 1999
	}
}
