using System;

namespace Microsoft.SqlServer.Server
{
	public enum TriggerAction
	{
		Invalid,
		Insert,
		Update,
		Delete,
		CreateTable = 21,
		AlterTable,
		DropTable,
		CreateIndex,
		AlterIndex,
		DropIndex,
		CreateSynonym = 34,
		DropSynonym = 36,
		CreateSecurityExpression = 31,
		DropSecurityExpression = 33,
		CreateView = 41,
		AlterView,
		DropView,
		CreateProcedure = 51,
		AlterProcedure,
		DropProcedure,
		CreateFunction = 61,
		AlterFunction,
		DropFunction,
		CreateTrigger = 71,
		AlterTrigger,
		DropTrigger,
		CreateEventNotification,
		DropEventNotification = 76,
		CreateType = 91,
		DropType = 93,
		CreateAssembly = 101,
		AlterAssembly,
		DropAssembly,
		CreateUser = 131,
		AlterUser,
		DropUser,
		CreateRole,
		AlterRole,
		DropRole,
		CreateAppRole,
		AlterAppRole,
		DropAppRole,
		CreateSchema = 141,
		AlterSchema,
		DropSchema,
		CreateLogin,
		AlterLogin,
		DropLogin,
		CreateMsgType = 151,
		DropMsgType = 153,
		CreateContract,
		DropContract = 156,
		CreateQueue,
		AlterQueue,
		DropQueue,
		CreateService = 161,
		AlterService,
		DropService,
		CreateRoute,
		AlterRoute,
		DropRoute,
		GrantStatement,
		DenyStatement,
		RevokeStatement,
		GrantObject,
		DenyObject,
		RevokeObject,
		CreateBinding = 174,
		AlterBinding,
		DropBinding,
		CreatePartitionFunction = 191,
		AlterPartitionFunction,
		DropPartitionFunction,
		CreatePartitionScheme,
		AlterPartitionScheme,
		DropPartitionScheme
	}
}
