using System;

namespace rail
{
	public enum RAILEventID
	{
		kRailEventBegin,
		kRailEventFinalize,
		kRailEventSystemStateChanged,
		kRailPlatformNotifyEventJoinGameByGameServer = 100,
		kRailPlatformNotifyEventJoinGameByRoom,
		kRailPlatformNotifyEventJoinGameByUser,
		kRailEventStats = 2000,
		kRailEventStatsPlayerStatsReceived,
		kRailEventStatsPlayerStatsStored,
		kRailEventStatsNumOfPlayerReceived,
		kRailEventStatsGlobalStatsReceived,
		kRailEventAchievement = 2100,
		kRailEventAchievementPlayerAchievementReceived,
		kRailEventAchievementPlayerAchievementStored,
		kRailEventAchievementGlobalAchievementReceived,
		kRailEventLeaderboard = 2200,
		kRailEventLeaderboardReceived,
		kRailEventLeaderboardEntryReceived,
		kRailEventLeaderboardUploaded,
		kRailEventLeaderboardAttachSpaceWork,
		kRailEventLeaderboardAsyncCreated,
		kRailEventGameServer = 3000,
		kRailEventGameServerListResult,
		kRailEventGameServerCreated,
		kRailEventGameServerSetMetadataResult,
		kRailEventGameServerGetMetadataResult,
		kRailEventGameServerGetSessionTicket,
		kRailEventGameServerAuthSessionTicket,
		kRailEventGameServerPlayerListResult,
		kRailEventGameServerRegisterToServerListResult,
		kRailEventGameServerFavoriteGameServers,
		kRailEventGameServerAddFavoriteGameServer,
		kRailEventGameServerRemoveFavoriteGameServer,
		kRailEventUserSpace = 4000,
		kRailEventUserSpaceGetMySubscribedWorksResult,
		kRailEventUserSpaceGetMyFavoritesWorksResult,
		kRailEventUserSpaceQuerySpaceWorksResult,
		kRailEventUserSpaceUpdateMetadataResult,
		kRailEventUserSpaceSyncResult,
		kRailEventUserSpaceSubscribeResult,
		kRailEventUserSpaceModifyFavoritesWorksResult,
		kRailEventUserSpaceRemoveSpaceWorkResult,
		kRailEventUserSpaceVoteSpaceWorkResult,
		kRailEventUserSpaceSearchSpaceWorkResult,
		kRailEventUserSpaceQuerySpaceWorksResultV2,
		kRailEventUserSpaceDownloadProgress,
		kRailEventUserSpaceDownloadResult,
		kRailEventUserSpaceRateSpaceWorkResult,
		kRailEventUserSpaceQuerySpaceWorksInfoResult,
		kRailEventNetChannel = 5000,
		kRailEventNetChannelCreateChannelResult,
		kRailEventNetChannelInviteJoinChannelRequest,
		kRailEventNetChannelJoinChannelResult,
		kRailEventNetChannelChannelException,
		kRailEventNetChannelChannelNetDelay,
		kRailEventNetChannelInviteMemmberResult,
		kRailEventNetChannelMemberStateChanged,
		kRailEventStorageBegin = 6000,
		kRailEventStorageQueryQuotaResult,
		kRailEventStorageShareToSpaceWorkResult,
		kRailEventStorageAsyncReadFileResult,
		kRailEventStorageAsyncWriteFileResult,
		kRailEventStorageAsyncListStreamFileResult,
		kRailEventStorageAsyncRenameStreamFileResult,
		kRailEventStorageAsyncDeleteStreamFileResult,
		kRailEventStorageAsyncReadStreamFileResult,
		kRailEventStorageAsyncWriteStreamFileResult,
		kRailEventAssetsBegin = 7000,
		kRailEventAssetsRequestAllAssetsFinished,
		kRailEventAssetsCompleteConsumeByExchangeAssetsToFinished,
		kRailEventAssetsExchangeAssetsFinished,
		kRailEventAssetsExchangeAssetsToFinished,
		kRailEventAssetsDirectConsumeFinished,
		kRailEventAssetsStartConsumeFinished,
		kRailEventAssetsUpdateConsumeFinished,
		kRailEventAssetsCompleteConsumeFinished,
		kRailEventAssetsSplitFinished,
		kRailEventAssetsSplitToFinished,
		kRailEventAssetsMergeFinished,
		kRailEventAssetsMergeToFinished,
		kRailEventAssetsRequestAllProductFinished,
		kRailEventAssetsUpdateAssetPropertyFinished,
		kRailEventAssetsAssetsChanged,
		kRailEventUtilsBegin = 8000,
		kRailEventUtilsSignatureResult = 8002,
		kRailEventUtilsGetImageDataResult,
		kRailEventUtilsGameSettingMetadataChanged,
		kRailEventInGamePurchaseBegin = 9000,
		kRailEventInGamePurchaseAllProductsInfoReceived,
		kRailEventInGamePurchaseAllPurchasableProductsInfoReceived,
		kRailEventInGamePurchasePurchaseProductsResult,
		kRailEventInGamePurchaseFinishOrderResult,
		kRailEventInGamePurchasePurchaseProductsToAssetsResult,
		kRailEventInGameStorePurchaseBegin = 9500,
		kRailEventInGameStorePurchasePayWindowDisplayed,
		kRailEventInGameStorePurchasePayWindowClosed,
		kRailEventInGameStorePurchasePaymentResult,
		kRailEventRoom = 10000,
		kRailEventRoomGetRoomListResult = 10002,
		kRailEventRoomCreated,
		kRailEventRoomGetRoomMembersResult,
		kRailEventRoomJoinRoomResult,
		kRailEventRoomKickOffMemberResult,
		kRailEventRoomSetRoomMetadataResult,
		kRailEventRoomGetRoomMetadataResult,
		kRailEventRoomGetMemberMetadataResult,
		kRailEventRoomSetMemberMetadataResult,
		kRailEventRoomLeaveRoomResult,
		kRailEventRoomGetAllDataResult,
		kRailEventRoomGetUserRoomListResult,
		kRailEventRoomClearRoomMetadataResult,
		kRailEventRoomOpenRoomResult,
		kRailEventRoomSetRoomTagResult,
		kRailEventRoomGetRoomTagResult,
		kRailEventRoomSetNewRoomOwnerResult,
		kRailEventRoomSetRoomTypeResult,
		kRailEventRoomSetRoomMaxMemberResult,
		kRailEventRoomNotify = 11000,
		kRailEventRoomNotifyMetadataChanged,
		kRailEventRoomNotifyMemberChanged,
		kRailEventRoomNotifyMemberkicked,
		kRailEventRoomNotifyRoomDestroyed,
		kRailEventRoomNotifyRoomOwnerChanged,
		kRailEventRoomNotifyRoomDataReceived,
		kRailEventRoomNotifyRoomGameServerChanged,
		kRailEventFriend = 12000,
		kRailEventFriendsDialogShow,
		kRailEventFriendsSetMetadataResult,
		kRailEventFriendsGetMetadataResult,
		kRailEventFriendsClearMetadataResult,
		kRailEventFriendsGetInviteCommandLine,
		kRailEventFriendsReportPlayedWithUserListResult,
		kRailEventFriendsFriendsListChanged = 12010,
		kRailEventFriendsGetFriendPlayedGamesResult,
		kRailEventFriendsQueryPlayedWithFriendsListResult,
		kRailEventFriendsQueryPlayedWithFriendsTimeResult,
		kRailEventFriendsQueryPlayedWithFriendsGamesResult,
		kRailEventFriendsAddFriendResult,
		kRailEventFriendsOnlineStateChanged,
		kRailEventFriendsMetadataChanged,
		kRailEventSessionTicket = 13000,
		kRailEventSessionTicketGetSessionTicket,
		kRailEventSessionTicketAuthSessionTicket,
		kRailEventPlayerGetGamePurchaseKey,
		kRailEventQueryPlayerBannedStatus,
		kRailEventPlayerGetAuthenticateURL,
		kRailEventPlayerAntiAddictionGameOnlineTimeChanged,
		kRailEventPlayerGetEncryptedGameTicketResult,
		kRailEventPlayerGetPlayerMetadataResult,
		kRailEventUsersGetUsersInfo = 13501,
		kRailEventUsersNotifyInviter,
		kRailEventUsersRespondInvitation,
		kRailEventUsersInviteJoinGameResult,
		kRailEventUsersInviteUsersResult,
		kRailEventUsersGetInviteDetailResult,
		kRailEventUsersCancelInviteResult,
		kRailEventUsersGetUserLimitsResult,
		kRailEventUsersShowChatWindowWithFriendResult,
		kRailEventUsersShowUserHomepageWindowResult,
		kRailEventShowFloatingWindow = 14000,
		kRailEventShowFloatingNotifyWindow,
		kRailEventBrowser = 15000,
		kRailEventBrowserCreateResult,
		kRailEventBrowserReloadResult,
		kRailEventBrowserCloseResult,
		kRailEventBrowserJavascriptEvent,
		kRailEventBrowserTryNavigateNewPageRequest,
		kRailEventBrowserPaint,
		kRailEventBrowserDamageRectPaint,
		kRailEventBrowserNavigeteResult,
		kRailEventBrowserStateChanged,
		kRailEventBrowserTitleChanged,
		kRailEventNetwork = 16000,
		kRailEventNetworkCreateSessionRequest,
		kRailEventNetworkCreateSessionFailed,
		kRailEventNetworkCreateRawSessionRequest,
		kRailEventNetworkCreateRawSessionFailed,
		kRailEventDlcBegin = 17000,
		kRailEventDlcInstallStart,
		kRailEventDlcInstallStartResult,
		kRailEventDlcInstallProgress,
		kRailEventDlcInstallFinished,
		kRailEventDlcUninstallFinished,
		kRailEventDlcCheckAllDlcsStateReadyResult,
		kRailEventDlcQueryIsOwnedDlcsResult,
		kRailEventDlcOwnershipChanged,
		kRailEventDlcRefundChanged,
		kRailEventScreenshot = 18000,
		kRailEventScreenshotTakeScreenshotFinished,
		kRailEventScreenshotTakeScreenshotRequest,
		kRailEventScreenshotPublishScreenshotFinished,
		kRailEventVoiceChannel = 19000,
		kRailEventVoiceChannelCreateResult,
		kRailEventVoiceChannelDataCaptured,
		kRailEventVoiceChannelJoinedResult,
		kRailEventVoiceChannelLeaveResult,
		kRailEventVoiceChannelAddUsersResult,
		kRailEventVoiceChannelRemoveUsersResult,
		kRailEventVoiceChannelInviteEvent,
		kRailEventVoiceChannelMemberChangedEvent,
		kRailEventVoiceChannelUsersSpeakingStateChangedEvent,
		kRailEventVoiceChannelPushToTalkKeyChangedEvent,
		kRailEventVoiceChannelSpeakingUsersChangedEvent,
		kRailEventAppBegin = 20000,
		kRailEventAppQuerySubscribeWishPlayStateResult,
		kRailEventTextInputBegin = 21000,
		kRailEventTextInputShowTextInputWindowResult,
		kRailEventIMEHelperTextInputBegin = 22000,
		kRailEventIMEHelperTextInputSelectedResult,
		kRailEventIMEHelperTextInputCompositionStateChanged,
		kRailEventHttpSessionBegin = 23000,
		kRailEventHttpSessionResponseResult,
		kRailEventSmallObjectServiceBegin = 24000,
		kRailEventSmallObjectServiceQueryObjectStateResult,
		kRailEventSmallObjectServiceDownloadResult,
		kRailEventZoneServerBegin = 25000,
		kRailEventZoneServerSwitchPlayerSelectedZoneResult,
		kRailEventGroupChatBegin = 26000,
		kRailEventGroupChatQueryGroupsInfoResult,
		kRailEventGroupChatOpenGroupChatResult,
		kRailEventInGameCoinBegin = 27000,
		kRailEventInGameCoinRequestCoinInfoResult,
		kRailEventInGameCoinPurchaseCoinsResult,
		kRailEventInGameActivityBegin = 28000,
		kRailEventInGameActivityQueryGameActivityResult,
		kRailEventInGameActivityOpenGameActivityWindowResult,
		kRailEventInGameActivityNotifyNewGameActivities,
		kRailEventInGameActivityGameActivityPlayerEvent,
		kRailEventAntiAddictionBegin = 29000,
		kRailEventAntiAddictionQueryGameOnlineTimeResult,
		kRailEventAntiAddictionCustomizeAntiAddictionActions,
		kRailThirdPartyAccountLoginBegin = 30000,
		kRailThirdPartyAccountLoginResult,
		kRailThirdPartyAccountLoginNotifyQrCodeInfo,
		kCustomEventBegin = 10000000
	}
}
