using System;

namespace rail
{
	public enum RailResult
	{
		kSuccess,
		kFailure = 1010001,
		kErrorInvalidParam,
		kErrorImageNotFound,
		kErrorBufferTooSmall,
		kErrorNetworkError,
		kErrorUnimplemented,
		kErrorInvalidCustomKey,
		kErrorClientInOfflineMode,
		kErrorParameterLengthTooLong,
		kErrorWebApiKeyNoAccessOnThisGame,
		kErrorOperationTimeout,
		kErrorServerResponseInvalid,
		kErrorServerInternalError,
		kErrorFileNotFound = 1011000,
		kErrorAccessDenied,
		kErrorOpenFileFailed,
		kErrorCreateFileFailed,
		kErrorReadFailed,
		kErrorWriteFailed,
		kErrorFileDestroyed,
		kErrorFileDelete,
		kErrorFileQueryIndexOutofRange,
		kErrorFileAvaiableQuotaMoreThanTotal,
		kErrorFileGetRemotePathError,
		kErrorFileIllegal,
		kErrorStreamFileWriteParamError,
		kErrorStreamFileReadParamError,
		kErrorStreamCloseErrorIOWritting,
		kErrorStreamCloseErrorIOReading,
		kErrorStreamDeleteFileOpenFileError,
		kErrorStreamRenameFileOpenFileError,
		kErrorStreamReadOnlyError,
		kErrorStreamCreateFileRemoveOldFileError,
		kErrorStreamCreateFileNameNotAvailable,
		kErrorStreamOpenFileErrorCloudStorageDisabledByPlatform,
		kErrorStreamOpenFileErrorCloudStorageDisabledByPlayer,
		kErrorStoragePathNotFound,
		kErrorStorageFileCantOpen,
		kErrorStorageFileRefuseAccess,
		kErrorStorageFileInvalidHandle,
		kErrorStorageFileInUsingByAnotherProcess,
		kErrorStorageFileLockedByAnotherProcess,
		kErrorStorageFileWriteDiskNotEnough,
		kErrorStorageFileCantCreateFileOrPath,
		kErrorRoomCreateFailed = 1012000,
		kErrorKickOffFailed,
		kErrorKickOffPlayerNotInRoom,
		kErrorKickOffNotRoomOwner,
		kErrorKickOffPlayingGame,
		kErrorRoomServerRequestInvalidData,
		kErrorRoomServerConnectTcaplusFail,
		kErrorRoomServerConnectTcaplusTimeOut,
		kErrorRoomServerWrongDataInTcaplus,
		kErrorRoomServerNoDataInTcaplus,
		kErrorRoomServerAllocateRoomIdFail,
		kErrorRoomServerCreateGroupInImCloudFail,
		kErrorRoomServerUserAlreadyInGame,
		kErrorRoomServerQueryResultEmpty,
		kErrorRoomServerRoomFull,
		kErrorRoomServerRoomNotExist,
		kErrorRoomServerUserAlreadyInRoom,
		kErrorRoomServerQueryRailIdServiceFail = 1012018,
		kErrorRoomServerImCloudFail,
		kErrorRoomServerPbSerializeFail,
		kErrorRoomServerDirtyWord,
		kErrorRoomServerNoPermission,
		kErrorRoomServerLeaveUserNotInRoom,
		kErrorRoomServerDestroiedRoomNotExist,
		kErrorRoomServerUserIsNotRoomMember,
		kErrorRoomServerLockFailed,
		kErrorRoomServerRouteMiss,
		kErrorRoomServerRetry,
		kErrorRoomSendDataNotImplemented,
		kErrorRoomInvokeFailed,
		kErrorRoomServerPasswordIncorrect,
		kErrorRoomServerRoomIsNotJoinable,
		kErrorStats = 1013000,
		kErrorStatsDontSetOtherPlayerStat,
		kErrorAchievement = 1014000,
		kErrorAchievementOutofRange,
		kErrorAchievementNotMyAchievement,
		kErrorLeaderboard = 1015000,
		kErrorLeaderboardNotExists,
		kErrorLeaderboardNotBePrepared,
		kErrorLeaderboardCreattionNotSupport,
		kErrorAssets = 1016000,
		kErrorAssetsPending,
		kErrorAssetsOK,
		kErrorAssetsExpired,
		kErrorAssetsInvalidParam,
		kErrorAssetsServiceUnavailable,
		kErrorAssetsLimitExceeded,
		kErrorAssetsFailed,
		kErrorAssetsRailIdInvalid,
		kErrorAssetsGameIdInvalid,
		kErrorAssetsRequestInvokeFailed,
		kErrorAssetsUpdateConsumeProgressNull,
		kErrorAssetsCanNotFindAssetId,
		kErrorAssetInvalidRequest,
		kErrorAssetDBFail,
		kErrorAssetDataTooOld,
		kErrorAssetInConsume,
		kErrorAssetNotExist,
		kErrorAssetExchangNotMatch,
		kErrorAssetSystemError,
		kErrorAssetBadJasonData,
		kErrorAssetStateNotConsuing,
		kErrorAssetStateConsuing,
		kErrorAssetDifferentProductId,
		kErrorAssetConsumeQuantityTooBig,
		kErrorAssetMissMatchRailId,
		kErrorAssetProductInfoNotReady,
		kErrorInGamePurchase = 1017000,
		kErrorInGamePurchaseProductInfoExpired,
		kErrorInGamePurchaseAcquireSessionTicketFailed,
		kErrorInGamePurchaseParseWebContentFaild,
		kErrorInGamePurchaseProductIsNotExist,
		kErrorInGamePurchaseOrderIDIsNotExist,
		kErrorInGamePurchasePreparePaymentRequestTimeout,
		kErrorInGamePurchaseCreateOrderFailed,
		kErrorInGamePurchaseQueryOrderFailed,
		kErrorInGamePurchaseFinishOrderFailed,
		kErrorInGamePurchasePaymentFailed,
		kErrorInGamePurchasePaymentCancle,
		kErrorInGamePurchaseCreatePaymentBrowserFailed,
		kErrorInGamePurchaseExceededProductPurchaseLimit,
		kErrorInGamePurchaseExceededPurchaseCountLimit,
		kErrorInGameStorePurchase = 1017500,
		kErrorInGameStorePurchasePaymentSuccess,
		kErrorInGameStorePurchasePaymentFailure,
		kErrorInGameStorePurchasePaymentCancle,
		kErrorPlayer = 1018000,
		kErrorPlayerUserFolderCreateFailed,
		kErrorPlayerUserFolderCanntFind,
		kErrorPlayerUserNotFriend,
		kErrorPlayerGameNotSupportPurchaseKey,
		kErrorPlayerGetAuthenticateURLFailed,
		kErrorPlayerGetAuthenticateURLServerError,
		kErrorPlayerGetAuthenticateURLInvalidURL,
		kErrorFriends = 1019000,
		kErrorFriendsKeyFrontUseRail,
		kErrorFriendsMetadataSizeInvalid,
		kErrorFriendsMetadataKeyLenInvalid,
		kErrorFriendsMetadataValueLenInvalid,
		kErrorFriendsMetadataKeyInvalid,
		kErrorFriendsGetMetadataFailed,
		kErrorFriendsSetPlayTogetherSizeZero,
		kErrorFriendsSetPlayTogetherContentSizeInvalid,
		kErrorFriendsInviteResponseTypeInvalid,
		kErrorFriendsListUpdateFailed,
		kErrorFriendsAddFriendInvalidID,
		kErrorFriendsAddFriendNetworkError,
		kErrorFriendsServerBusy,
		kErrorFriendsUpdateFriendsListTooFrequent,
		kErrorSessionTicket = 1020000,
		kErrorSessionTicketGetTicketFailed,
		kErrorSessionTicketAuthFailed,
		kErrorSessionTicketAuthTicketAbandoned,
		kErrorSessionTicketAuthTicketExpire,
		kErrorSessionTicketAuthTicketInvalid,
		kErrorSessionTicketInvalidParameter = 1020500,
		kErrorSessionTicketInvalidTicket,
		kErrorSessionTicketIncorrectTicketOwner,
		kErrorSessionTicketHasBeenCanceledByTicketOwner,
		kErrorSessionTicketExpired,
		kErrorFloatWindow = 1021000,
		kErrorFloatWindowInitFailed,
		kErrorFloatWindowShowStoreInvalidPara,
		kErrorFloatWindowShowStoreCreateBrowserFailed,
		kErrorUserSpace = 1022000,
		kErrorUserSpaceGetWorkDetailFailed,
		kErrorUserSpaceDownloadError,
		kErrorUserSpaceDescFileInvalid,
		kErrorUserSpaceReplaceOldFileFailed,
		kErrorUserSpaceUserCancelSync,
		kErrorUserSpaceIDorUserdataPathInvalid,
		kErrorUserSpaceNoData,
		kErrorUserSpaceSpaceWorkIDInvalid,
		kErrorUserSpaceNoSyncingNow,
		kErrorUserSpaceSpaceWorkAlreadySyncing,
		kErrorUserSpaceSubscribePartialSuccess,
		kErrorUserSpaceNoVersionField,
		kErrorUserSpaceUpdateFailedWhenUploading,
		kErrorUserSpaceGetTicketFailed,
		kErrorUserSpaceVersionOccupied,
		kErrorUserSpaceCallCreateMethodFailed,
		kErrorUserSpaceCreateMethodRspFailed,
		kErrorUserSpaceNoEditablePermission = 1022020,
		kErrorUserSpaceCallEditMethodFailed,
		kErrorUserSpaceEditMethodRspFailed,
		kErrorUserSpaceMetadataHasInvalidKey,
		kErrorUserSpaceModifyFavoritePartialSuccess,
		kErrorUserSpaceFilePathTooLong,
		kErrorUserSpaceInvalidContentFolder,
		kErrorUserSpaceInvalidFilePath,
		kErrorUserSpaceUploadFileNotMeetLimit,
		kErrorUserSpaceCannotReadFileToBeUploaded,
		kErrorUserSpaceUploadSpaceWorkHasNoVersionField,
		kErrorUserSpaceDownloadCurrentDescFileFailed,
		kErrorUserSpaceCannotGetSpaceWorkDownloadUrl,
		kErrorUserSpaceCannotGetSpaceWorkUploadUrl,
		kErrorUserSpaceCannotReadFileWhenUploading,
		kErrorUserSpaceUploadFileTooLarge,
		kErrorUserSpaceUploadRequestTimeout,
		kErrorUserSpaceUploadRequestFailed,
		kErrorUserSpaceUploadInternalError,
		kErrorUserSpaceUploadCloudServerError,
		kErrorUserSpaceUploadCloudServerRspInvalid,
		kErrorUserSpaceUploadCopyNoExistCloudFile,
		kErrorUserSpaceShareLevelNotSatisfied,
		kErrorUserSpaceHasntBeenApproved,
		kErrorUserSpaceCanNotLoadCacheFromLocalFile,
		kErrorUserSpaceV2NoDownloadURL,
		kErrorUserSpaceV2DownloadDescriptionFilePerformFailed,
		kErrorUserSpaceV2DescriptionFileParseResponseNotJson,
		kErrorUserSpaceV2DescriptionFileParseJsonError,
		kErrorUserSpaceV2CheckDownloadContentFailed,
		kErrorUserSpaceV2OfflineMode,
		kErrorUserSpaceV2CannotAccessUserDataPath,
		kErrorUserSpaceV2CleanInvalidFilesFailed,
		kErrorUserSpaceV2GeneratePreviewPathFailed,
		kErrorUserSpaceV2LocalFilesAreLatestVersion,
		kErrorUserSpaceV2DownloadFilesFailed,
		kErrorUserSpaceV2HelperInvokeFailed,
		kErrorUserSpaceV2HelperInvokeRetFailed,
		kErrorUserSpaceV2HelperNoCache,
		kErrorUserSpaceV2HelperQueryDetailInfoFailed,
		kErrorUserSpaceV2HelperNoFilesNeedDownload,
		kErrorUserSpaceV2WriteDescriptionFileFailed,
		kErrorUserSpaceV2FilePathTooLong,
		kErrorUserSpaceV2ResumeDownloadFromBreakpointFailed,
		kErrorUserSpaceV2CannotFindTaskIdInResumeDownloadList,
		kErrorUserSpaceV2CancelAllDownloadByUser,
		kErrorUserSpaceV2AlreadyInDownloading,
		kErrorUserSpaceV2TenioDLError,
		kErrorUserSpaceV2EnumEnd,
		kErrorUserSpaceV2QueriedSpaceWorksAmountExceedLimit,
		kErrorGameServer = 1023000,
		kErrorGameServerCreateFailed,
		kErrorGameServerDisconnectedServerlist,
		kErrorGameServerConnectServerlistFailure,
		kErrorGameServerSetMetadataFailed,
		kErrorGameServerGetMetadataFailed,
		kErrorGameServerGetServerListFailed,
		kErrorGameServerGetPlayerListFailed,
		kErrorGameServerPlayerNotJoinGameserver,
		kErrorGameServerNeedGetFovariteFirst,
		kErrorGameServerAddFovariteFailed,
		kErrorGameServerRemoveFovariteFailed,
		kErrorNetwork = 1024000,
		kErrorNetworkInitializeFailed,
		kErrorNetworkSessionIsNotExist,
		kErrorNetworkNoAvailableDataToRead,
		kErrorNetworkUnReachable,
		kErrorNetworkRemotePeerOffline,
		kErrorNetworkServerUnavailabe,
		kErrorNetworkConnectionDenied,
		kErrorNetworkConnectionClosed,
		kErrorNetworkConnectionReset,
		kErrorNetworkSendDataSizeTooLarge,
		kErrorNetworkSessioNotRegistered,
		kErrorNetworkSessionTimeout,
		kErrorDlc = 1025000,
		kErrorDlcInstallFailed,
		kErrorDlcUninstallFailed,
		kErrorDlcGetDlcListTimeout,
		kErrorDlcRequestInvokeFailed,
		kErrorDlcRequestToofrequently,
		kErrorUtils = 1026000,
		kErrorUtilsImagePathNull,
		kErrorUtilsImagePathInvalid,
		kErrorUtilsImageDownloadFail,
		kErrorUtilsImageOpenLocalFail,
		kErrorUtilsImageBufferAllocateFail,
		kErrorUtilsImageReadLocalFail,
		kErrorUtilsImageParseFail,
		kErrorUtilsImageScaleFail,
		kErrorUtilsImageUnknownFormat,
		kErrorUtilsImageNotNeedResize,
		kErrorUtilsImageResizeParameterInvalid,
		kErrorUtilsImageSaveFileFail,
		kErrorUtilsDirtyWordsFilterTooManyInput,
		kErrorUtilsDirtyWordsHasInvalidString,
		kErrorUtilsDirtyWordsNotReady,
		kErrorUtilsDirtyWordsDllUnloaded,
		kErrorUtilsCrashAllocateFailed,
		kErrorUtilsCrashCallbackSwitchOff,
		kErrorUsers = 1027000,
		kErrorUsersInvalidInviteCommandLine,
		kErrorUsersSetCommandLineFailed,
		kErrorUsersInviteListEmpty,
		kErrorUsersGenerateRequestFail,
		kErrorUsersUnknownInviteType,
		kErrorUsersInvalidInviteUsersSize,
		kErrorScreenshot = 1028000,
		kErrorScreenshotWorkNotExist,
		kErrorScreenshotCantConvertPng,
		kErrorScreenshotCopyFileFailed,
		kErrorScreenshotCantCreateThumbnail,
		kErrorVoiceCapture = 1029000,
		kErrorVoiceCaptureInitializeFailed,
		kErrorVoiceCaptureDeviceLost,
		kErrorVoiceCaptureIsRecording,
		kErrorVoiceCaptureNotRecording,
		kErrorVoiceCaptureNoData,
		kErrorVoiceCaptureMoreData,
		kErrorVoiceCaptureDataCorrupted,
		kErrorVoiceCapturekUnsupportedCodec,
		kErrorVoiceChannelHelperNotReady,
		kErrorVoiceChannelIsBusy,
		kErrorVoiceChannelNotJoinedChannel,
		kErrorVoiceChannelLostConnection,
		kErrorVoiceChannelAlreadyJoinedAnotherChannel,
		kErrorVoiceChannelPartialSuccess,
		kErrorVoiceChannelNotTheChannelOwner,
		kErrorTextInputTextInputSendMessageToPlatformFailed = 1040000,
		kErrorTextInputTextInputSendMessageToOverlayFailed,
		kErrorTextInputTextInputUserCanceled,
		kErrorTextInputTextInputEnableChineseFailed,
		kErrorTextInputTextInputShowFailed,
		kErrorTextInputEnableIMEHelperTextInputWindowFailed,
		kErrorApps = 1041000,
		kErrorAppsCountingKeyExists,
		kErrorAppsCountingKeyDoesNotExist,
		kErrorHttpSession = 1042000,
		kErrorHttpSessionPostBodyContentConflictWithPostParameter,
		kErrorHttpSessionRequestMehotdNotPost,
		kErrorSmallObjectService = 1043000,
		kErrorSmallObjectServiceObjectNotExist,
		kErrorSmallObjectServiceFailedToRequestDownload,
		kErrorSmallObjectServiceDownloadFailed,
		kErrorSmallObjectServiceFailedToWriteDisk,
		kErrorSmallObjectServiceFailedToUpdateObject,
		kErrorSmallObjectServicePartialDownloadSuccess,
		kErrorSmallObjectServiceObjectNetworkIssue,
		kErrorSmallObjectServiceObjectServerError,
		kErrorSmallObjectServiceInvalidBranch,
		kErrorZoneServer = 1044000,
		kErrorZoneServerValueDataIsNotExist,
		kErrorInGameCoin = 1045000,
		kErrorInGameCoinCreatePaymentBrowserFailed,
		kErrorInGameCoinOperationTimeout,
		kErrorInGameCoinPaymentFailed,
		kErrorInGameCoinPaymentCanceled,
		kErrorInGameCoinConfigurationNotAvailable,
		kErrorInGameActivity = 1046000,
		kErrorInGameActivityNoConfigurationInfo,
		kErrorInGameActivityInvalidConfigurationInfo,
		kErrorInGameActivityNoDefaultActivityWindow,
		kErrorInGameActivityNoSuchActivityID,
		kErrorInGameActivityOpenGameActivityWindowFailed,
		kErrorInGameActivityOpenGameActivityWindowTimeout,
		kErrorThirdPartyAccountLogin = 1047000,
		kErrorThirdPartyAccountLoginAutoLoginNotSupport,
		kErrorThirdPartyAccountLoginAccountTypeNotSupportAutoLogin,
		kRailErrorServerBegin = 2000000,
		kErrorPaymentSystem = 2080001,
		kErrorPaymentParameterIlleage = 2080008,
		kErrorPaymentOrderIlleage = 2080011,
		kErrorAssetsInvalidParameter = 2230001,
		kErrorAssetsSystemError = 2230007,
		kErrorDirtyWordsFilterNoPermission = 2290028,
		kErrorDirtyWordsFilterCheckFailed,
		kErrorDirtyWordsFilterSystemBusy,
		kRailErrorInnerServerBegin = 2500000,
		kErrorGameGrayCheckSnowError,
		kErrorGameGrayParameterIlleage,
		kErrorGameGraySystemError,
		kErrorGameGrayQQToWegameidError,
		kRailErrorInnerServerEnd = 2699999,
		kRailErrorServerEnd = 2999999
	}
}
