using System;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using UnityEngine.Scripting;

namespace UnityEngine.Experimental.GlobalIllumination
{
	/// <summary>
	///   <para>Interface to the light baking backends.</para>
	/// </summary>
	public static class Lightmapping
	{
		public static void SetDelegate(Lightmapping.RequestLightsDelegate del)
		{
			Lightmapping.s_RequestLightsDelegate = ((del == null) ? Lightmapping.s_DefaultDelegate : del);
		}

		/// <summary>
		///   <para>Resets the light conversion delegate to Unity's default conversion function.</para>
		/// </summary>
		public static void ResetDelegate()
		{
			Lightmapping.s_RequestLightsDelegate = Lightmapping.s_DefaultDelegate;
		}

		[UsedByNativeCode]
		internal unsafe static void RequestLights(Light[] lights, IntPtr outLightsPtr, int outLightsCount)
		{
			NativeArray<LightDataGI> nativeArray = NativeArrayUnsafeUtility.ConvertExistingDataToNativeArray<LightDataGI>((void*)outLightsPtr, outLightsCount, Allocator.None);
			Lightmapping.s_RequestLightsDelegate(lights, nativeArray);
		}

		private static readonly Lightmapping.RequestLightsDelegate s_DefaultDelegate = delegate(Light[] requests, NativeArray<LightDataGI> lightsOutput)
		{
			DirectionalLight directionalLight = default(DirectionalLight);
			PointLight pointLight = default(PointLight);
			SpotLight spotLight = default(SpotLight);
			RectangleLight rectangleLight = default(RectangleLight);
			LightDataGI lightDataGI = default(LightDataGI);
			for (int i = 0; i < requests.Length; i++)
			{
				Light light = requests[i];
				switch (light.type)
				{
				case LightType.Spot:
					LightmapperUtils.Extract(light, ref spotLight);
					lightDataGI.Init(ref spotLight);
					break;
				case LightType.Directional:
					LightmapperUtils.Extract(light, ref directionalLight);
					lightDataGI.Init(ref directionalLight);
					break;
				case LightType.Point:
					LightmapperUtils.Extract(light, ref pointLight);
					lightDataGI.Init(ref pointLight);
					break;
				case LightType.Area:
					LightmapperUtils.Extract(light, ref rectangleLight);
					lightDataGI.Init(ref rectangleLight);
					break;
				default:
					lightDataGI.InitNoBake(light.GetInstanceID());
					break;
				}
				lightsOutput[i] = lightDataGI;
			}
		};

		private static Lightmapping.RequestLightsDelegate s_RequestLightsDelegate = Lightmapping.s_DefaultDelegate;

		/// <summary>
		///   <para>Delegate called when converting lights into a form that the baking backends understand.</para>
		/// </summary>
		/// <param name="requests">The list of lights to be converted.</param>
		/// <param name="lightsOutput">The output generated by the delegate function. Lights that should be skipped must be added to the output, initialized with InitNoBake on the LightDataGI structure.</param>
		public delegate void RequestLightsDelegate(Light[] requests, NativeArray<LightDataGI> lightsOutput);
	}
}
