using System;

namespace System.Drawing.Imaging
{
	public enum EmfPlusRecordType
	{
		WmfRecordBase = 65536,
		WmfSetBkColor = 66049,
		WmfSetBkMode = 65794,
		WmfSetMapMode,
		WmfSetROP2,
		WmfSetRelAbs,
		WmfSetPolyFillMode,
		WmfSetStretchBltMode,
		WmfSetTextCharExtra,
		WmfSetTextColor = 66057,
		WmfSetTextJustification,
		WmfSetWindowOrg,
		WmfSetWindowExt,
		WmfSetViewportOrg,
		WmfSetViewportExt,
		WmfOffsetWindowOrg,
		WmfScaleWindowExt = 66576,
		WmfOffsetViewportOrg = 66065,
		WmfScaleViewportExt = 66578,
		WmfLineTo = 66067,
		WmfMoveTo,
		WmfExcludeClipRect = 66581,
		WmfIntersectClipRect,
		WmfArc = 67607,
		WmfEllipse = 66584,
		WmfFloodFill,
		WmfPie = 67610,
		WmfRectangle = 66587,
		WmfRoundRect = 67100,
		WmfPatBlt,
		WmfSaveDC = 65566,
		WmfSetPixel = 66591,
		WmfOffsetCilpRgn = 66080,
		WmfTextOut = 66849,
		WmfBitBlt = 67874,
		WmfStretchBlt = 68387,
		WmfPolygon = 66340,
		WmfPolyline,
		WmfEscape = 67110,
		WmfRestoreDC = 65831,
		WmfFillRegion = 66088,
		WmfFrameRegion = 66601,
		WmfInvertRegion = 65834,
		WmfPaintRegion,
		WmfSelectClipRegion,
		WmfSelectObject,
		WmfSetTextAlign,
		WmfChord = 67632,
		WmfSetMapperFlags = 66097,
		WmfExtTextOut = 68146,
		WmfSetDibToDev = 68915,
		WmfSelectPalette = 66100,
		WmfRealizePalette = 65589,
		WmfAnimatePalette = 66614,
		WmfSetPalEntries = 65591,
		WmfPolyPolygon = 66872,
		WmfResizePalette = 65849,
		WmfDibBitBlt = 67904,
		WmfDibStretchBlt = 68417,
		WmfDibCreatePatternBrush = 65858,
		WmfStretchDib = 69443,
		WmfExtFloodFill = 66888,
		WmfSetLayout = 65865,
		WmfDeleteObject = 66032,
		WmfCreatePalette = 65783,
		WmfCreatePatternBrush = 66041,
		WmfCreatePenIndirect = 66298,
		WmfCreateFontIndirect,
		WmfCreateBrushIndirect,
		WmfCreateRegion = 67327,
		EmfHeader = 1,
		EmfPolyBezier,
		EmfPolygon,
		EmfPolyline,
		EmfPolyBezierTo,
		EmfPolyLineTo,
		EmfPolyPolyline,
		EmfPolyPolygon,
		EmfSetWindowExtEx,
		EmfSetWindowOrgEx,
		EmfSetViewportExtEx,
		EmfSetViewportOrgEx,
		EmfSetBrushOrgEx,
		EmfEof,
		EmfSetPixelV,
		EmfSetMapperFlags,
		EmfSetMapMode,
		EmfSetBkMode,
		EmfSetPolyFillMode,
		EmfSetROP2,
		EmfSetStretchBltMode,
		EmfSetTextAlign,
		EmfSetColorAdjustment,
		EmfSetTextColor,
		EmfSetBkColor,
		EmfOffsetClipRgn,
		EmfMoveToEx,
		EmfSetMetaRgn,
		EmfExcludeClipRect,
		EmfIntersectClipRect,
		EmfScaleViewportExtEx,
		EmfScaleWindowExtEx,
		EmfSaveDC,
		EmfRestoreDC,
		EmfSetWorldTransform,
		EmfModifyWorldTransform,
		EmfSelectObject,
		EmfCreatePen,
		EmfCreateBrushIndirect,
		EmfDeleteObject,
		EmfAngleArc,
		EmfEllipse,
		EmfRectangle,
		EmfRoundRect,
		EmfRoundArc,
		EmfChord,
		EmfPie,
		EmfSelectPalette,
		EmfCreatePalette,
		EmfSetPaletteEntries,
		EmfResizePalette,
		EmfRealizePalette,
		EmfExtFloodFill,
		EmfLineTo,
		EmfArcTo,
		EmfPolyDraw,
		EmfSetArcDirection,
		EmfSetMiterLimit,
		EmfBeginPath,
		EmfEndPath,
		EmfCloseFigure,
		EmfFillPath,
		EmfStrokeAndFillPath,
		EmfStrokePath,
		EmfFlattenPath,
		EmfWidenPath,
		EmfSelectClipPath,
		EmfAbortPath,
		EmfReserved069,
		EmfGdiComment,
		EmfFillRgn,
		EmfFrameRgn,
		EmfInvertRgn,
		EmfPaintRgn,
		EmfExtSelectClipRgn,
		EmfBitBlt,
		EmfStretchBlt,
		EmfMaskBlt,
		EmfPlgBlt,
		EmfSetDIBitsToDevice,
		EmfStretchDIBits,
		EmfExtCreateFontIndirect,
		EmfExtTextOutA,
		EmfExtTextOutW,
		EmfPolyBezier16,
		EmfPolygon16,
		EmfPolyline16,
		EmfPolyBezierTo16,
		EmfPolylineTo16,
		EmfPolyPolyline16,
		EmfPolyPolygon16,
		EmfPolyDraw16,
		EmfCreateMonoBrush,
		EmfCreateDibPatternBrushPt,
		EmfExtCreatePen,
		EmfPolyTextOutA,
		EmfPolyTextOutW,
		EmfSetIcmMode,
		EmfCreateColorSpace,
		EmfSetColorSpace,
		EmfDeleteColorSpace,
		EmfGlsRecord,
		EmfGlsBoundedRecord,
		EmfPixelFormat,
		EmfDrawEscape,
		EmfExtEscape,
		EmfStartDoc,
		EmfSmallTextOut,
		EmfForceUfiMapping,
		EmfNamedEscpae,
		EmfColorCorrectPalette,
		EmfSetIcmProfileA,
		EmfSetIcmProfileW,
		EmfAlphaBlend,
		EmfSetLayout,
		EmfTransparentBlt,
		EmfReserved117,
		EmfGradientFill,
		EmfSetLinkedUfis,
		EmfSetTextJustification,
		EmfColorMatchToTargetW,
		EmfCreateColorSpaceW,
		EmfMax = 122,
		EmfMin = 1,
		EmfPlusRecordBase = 16384,
		Invalid = 16384,
		Header,
		EndOfFile,
		Comment,
		GetDC,
		MultiFormatStart,
		MultiFormatSection,
		MultiFormatEnd,
		Object,
		Clear,
		FillRects,
		DrawRects,
		FillPolygon,
		DrawLines,
		FillEllipse,
		DrawEllipse,
		FillPie,
		DrawPie,
		DrawArc,
		FillRegion,
		FillPath,
		DrawPath,
		FillClosedCurve,
		DrawClosedCurve,
		DrawCurve,
		DrawBeziers,
		DrawImage,
		DrawImagePoints,
		DrawString,
		SetRenderingOrigin,
		SetAntiAliasMode,
		SetTextRenderingHint,
		SetTextContrast,
		SetInterpolationMode,
		SetPixelOffsetMode,
		SetCompositingMode,
		SetCompositingQuality,
		Save,
		Restore,
		BeginContainer,
		BeginContainerNoParams,
		EndContainer,
		SetWorldTransform,
		ResetWorldTransform,
		MultiplyWorldTransform,
		TranslateWorldTransform,
		ScaleWorldTransform,
		RotateWorldTransform,
		SetPageTransform,
		ResetClip,
		SetClipRect,
		SetClipPath,
		SetClipRegion,
		OffsetClip,
		DrawDriverString,
		Total,
		Max = 16438,
		Min = 16385
	}
}
