using System;

namespace Mono.Unix.Native
{
	[Map]
	[CLSCompliant(false)]
	public enum UnixSocketOptionName
	{
		SO_DEBUG = 1,
		SO_REUSEADDR,
		SO_TYPE,
		SO_ERROR,
		SO_DONTROUTE,
		SO_BROADCAST,
		SO_SNDBUF,
		SO_RCVBUF,
		SO_SNDBUFFORCE = 32,
		SO_RCVBUFFORCE,
		SO_KEEPALIVE = 9,
		SO_OOBINLINE,
		SO_NO_CHECK,
		SO_PRIORITY,
		SO_LINGER,
		SO_BSDCOMPAT,
		SO_REUSEPORT,
		SO_PASSCRED,
		SO_PEERCRED,
		SO_RCVLOWAT,
		SO_SNDLOWAT,
		SO_RCVTIMEO,
		SO_SNDTIMEO,
		SO_SECURITY_AUTHENTICATION,
		SO_SECURITY_ENCRYPTION_TRANSPORT,
		SO_SECURITY_ENCRYPTION_NETWORK,
		SO_BINDTODEVICE,
		SO_ATTACH_FILTER,
		SO_DETACH_FILTER,
		SO_PEERNAME,
		SO_TIMESTAMP,
		SO_ACCEPTCONN,
		SO_PEERSEC,
		SO_PASSSEC = 34,
		SO_TIMESTAMPNS,
		SO_MARK,
		SO_TIMESTAMPING,
		SO_PROTOCOL,
		SO_DOMAIN,
		SO_RXQ_OVFL,
		SO_WIFI_STATUS,
		SO_PEEK_OFF,
		SO_NOFCS,
		SO_LOCK_FILTER,
		SO_SELECT_ERR_QUEUE,
		SO_BUSY_POLL,
		SO_MAX_PACING_RATE
	}
}
