using System;

namespace Unity.Burst
{
	internal enum DiagnosticId
	{
		ERR_InternalCompilerErrorInBackend = 100,
		ERR_InternalCompilerErrorInFunction,
		ERR_InternalCompilerErrorInInstruction,
		ERR_OnlyStaticMethodsAllowed = 1000,
		ERR_UnableToAccessManagedMethod,
		ERR_UnableToFindInterfaceMethod,
		ERR_UnexpectedEmptyMethodBody,
		ERR_ManagedArgumentsNotSupported,
		ERR_CatchConstructionNotSupported = 1006,
		ERR_CatchAndFilterConstructionNotSupported,
		ERR_LdfldaWithFixedArrayExpected,
		ERR_PointerExpected,
		ERR_LoadingFieldFromManagedObjectNotSupported,
		ERR_LoadingFieldWithManagedTypeNotSupported,
		ERR_LoadingArgumentWithManagedTypeNotSupported,
		ERR_CallingBurstDiscardMethodWithReturnValueNotSupported = 1015,
		ERR_CallingManagedMethodNotSupported,
		ERR_InstructionUnboxNotSupported = 1019,
		ERR_InstructionBoxNotSupported,
		ERR_InstructionNewobjWithManagedTypeNotSupported,
		ERR_AccessingManagedArrayNotSupported,
		ERR_InstructionLdtokenFieldNotSupported,
		ERR_InstructionLdtokenMethodNotSupported,
		ERR_InstructionLdtokenTypeNotSupported,
		ERR_InstructionLdtokenNotSupported,
		ERR_InstructionLdvirtftnNotSupported,
		ERR_InstructionNewarrNotSupported,
		ERR_InstructionRethrowNotSupported,
		ERR_InstructionCastclassNotSupported,
		ERR_InstructionLdftnNotSupported = 1032,
		ERR_InstructionLdstrNotSupported,
		ERR_InstructionStsfldNotSupported,
		ERR_InstructionEndfilterNotSupported,
		ERR_InstructionEndfinallyNotSupported,
		ERR_InstructionLeaveNotSupported,
		ERR_InstructionNotSupported,
		ERR_LoadingFromStaticFieldNotSupported,
		ERR_LoadingFromNonReadonlyStaticFieldNotSupported,
		ERR_LoadingFromManagedStaticFieldNotSupported,
		ERR_LoadingFromManagedNonReadonlyStaticFieldNotSupported,
		ERR_InstructionStfldToManagedObjectNotSupported,
		ERR_InstructionLdlenNonConstantLengthNotSupported,
		ERR_StructWithAutoLayoutNotSupported,
		ERR_StructWithGenericParametersAndExplicitLayoutNotSupported = 1047,
		ERR_StructSizeNotSupported,
		ERR_StructZeroSizeNotSupported,
		ERR_MarshalAsOnFieldNotSupported,
		ERR_TypeNotSupported,
		ERR_RequiredTypeModifierNotSupported,
		ERR_ErrorWhileProcessingVariable,
		ERR_UnableToResolveType,
		ERR_UnableToResolveMethod,
		ERR_ConstructorNotSupported,
		ERR_FunctionPointerMethodMissingBurstCompileAttribute,
		ERR_FunctionPointerTypeMissingBurstCompileAttribute,
		ERR_FunctionPointerMethodAndTypeMissingBurstCompileAttribute,
		INF_FunctionPointerMethodAndTypeMissingMonoPInvokeCallbackAttribute = 10590,
		ERR_MarshalAsOnParameterNotSupported = 1061,
		ERR_MarshalAsOnReturnTypeNotSupported,
		ERR_TypeNotBlittableForFunctionPointer,
		ERR_StructByValueNotSupported,
		ERR_StructsWithNonUnicodeCharsNotSupported = 1066,
		ERR_VectorsByValueNotSupported,
		ERR_MissingExternBindings,
		ERR_MarshalAsNativeTypeOnReturnTypeNotSupported,
		ERR_AssertTypeNotSupported = 1071,
		ERR_StoringToReadOnlyFieldNotAllowed,
		ERR_StoringToFieldInReadOnlyParameterNotAllowed,
		ERR_StoringToReadOnlyParameterNotAllowed,
		ERR_TypeManagerStaticFieldNotCompatible,
		ERR_UnableToFindTypeIndexForTypeManagerType,
		ERR_UnableToFindFieldForTypeManager,
		ERR_CircularStaticConstructorUsage = 1090,
		ERR_ExternalInternalCallsInStaticConstructorsNotSupported,
		ERR_PlatformNotSupported,
		ERR_InitModuleVerificationError,
		ERR_ModuleVerificationError,
		ERR_UnableToFindTypeRequiredForTypeManager,
		ERR_UnexpectedIntegerTypesForBinaryOperation,
		ERR_BinaryOperationNotSupported,
		ERR_CalliWithThisNotSupported,
		ERR_CalliNonCCallingConventionNotSupported,
		ERR_StringLiteralTooBig,
		ERR_LdftnNonCCallingConventionNotSupported,
		ERR_UnableToCallMethodOnInterfaceObject,
		ERR_UnsupportedCpuDependentBranch = 1199,
		ERR_InstructionTargetCpuFeatureNotAllowedInThisBlock,
		ERR_AssumeRangeTypeMustBeInteger,
		ERR_AssumeRangeTypeMustBeSameSign,
		ERR_UnsupportedSpillTransform = 1300,
		ERR_UnsupportedSpillTransformTooManyUsers,
		ERR_MethodNotSupported,
		ERR_VectorsLoadFieldIsAddress,
		ERR_ConstantExpressionRequired,
		WRN_HWInstrinsicsWithFPDeterminism,
		ERR_PointerArgumentsUnexpectedAliasing = 1310,
		ERR_LoopIntrinsicMustBeCalledInsideLoop = 1320,
		ERR_LoopUnexpectedAutoVectorization,
		WRN_LoopIntrinsicCalledButLoopOptimizedAway,
		ERR_AssertArgTypesDiffer = 1330,
		ERR_StringInternalCompilerFixedStringTooManyUsers = 1340,
		ERR_StringInvalidFormatMissingClosingBrace,
		ERR_StringInvalidIntegerForArgumentIndex,
		ERR_StringInvalidFormatForArgument,
		ERR_StringArgumentIndexOutOfRange,
		ERR_StringInvalidArgumentType,
		ERR_DebugLogNotSupported,
		ERR_StringInvalidNonLiteralFormat,
		ERR_StringInvalidStringFormatMethod,
		ERR_StringInvalidArgument,
		ERR_StringArrayInvalidArrayCreation,
		ERR_StringArrayInvalidArraySize,
		ERR_StringArrayInvalidControlFlow,
		ERR_StringArrayInvalidArrayIndex,
		ERR_StringArrayInvalidArrayIndexOutOfRange,
		ERR_UnmanagedStringMethodMissing,
		ERR_UnmanagedStringMethodInvalid,
		ERR_ManagedStaticConstructor = 1360,
		ERR_StaticConstantArrayInStaticConstructor,
		WRN_ExceptionThrownInNonSafetyCheckGuardedFunction = 1370,
		WRN_ACallToMethodHasBeenDiscarded,
		ERR_AccessingNestedManagedArrayNotSupported = 1380,
		ERR_LdobjFromANonPointerNonReference,
		ERR_StringLiteralRequired,
		ERR_MultiDimensionalArrayUnsupported,
		ERR_NonBlittableAndNonManagedSequentialStructNotSupported,
		ERR_VarArgFunctionNotSupported
	}
}
